
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '1 Tangled(라푼젤) - When Will My Life Begin', 'file': 'https://docs.google.com/uc?id=1-SUtYu2ErhgTXvrziM0NtPNofwbGFjHJ' },
        { 'icon': iconImage, 'title': '2 오빠야', 'file': 'https://docs.google.com/uc?id=119iddX1f5ygf_gHWUeXT5dBXBfz7vlZB' },
        { 'icon': iconImage, 'title': '있잖아', 'file': 'https://docs.google.com/uc?id=1AkwfaeB7sYDl8aPACSQZ7Eo2X76tghuh' },
        { 'icon': iconImage, 'title': '4 홍련화', 'file': 'https://docs.google.com/uc?id=1tkZXMqpjN1YzOZLh4pdEzFTtlRakTdBX' },
        { 'icon': iconImage, 'title': '5 Eight', 'file': 'https://docs.google.com/uc?id=1MuvajD-z-s3Hxa2qeCy38w4BlOGgxdsd' },
        { 'icon': iconImage, 'title': '6 소나기', 'file': 'https://docs.google.com/uc?id=1fKshUVeTZKGtv1ArgM2Rp-NDu_DBr1yY' },
        { 'icon': iconImage, 'title': '7 천양 다이노스', 'file': 'https://docs.google.com/uc?id=1VKQLTF9oV3nZnCNMCCSApqZwoqXcWTDQ' },
        { 'icon': iconImage, 'title': '8 프리스타일 랩', 'file': 'https://docs.google.com/uc?id=1D7O9rkouDJWnI8ddo41B-sC8QhTTKrPH' },
        { 'icon': iconImage, 'title': '9 rewind', 'file': 'https://docs.google.com/uc?id=1u99c_fCXg5JzK0UAMn6IR5jbGez3xxMR' },
        { 'icon': iconImage, 'title': '10 rewind 랩버전', 'file': 'https://docs.google.com/uc?id=15FRuPIBMGTQc5lTUOi-sA95QvpvGtIoV' },
        { 'icon': iconImage, 'title': '10cm - 사랑은 은하수 다방에서', 'file': 'https://docs.google.com/uc?id=1-pfMufFl8duI3Gk_a3pKR1rXp4SyCgVU' },
        { 'icon': iconImage, 'title': '10cm - 폰서트', 'file': 'https://docs.google.com/uc?id=1qt7jFSxHO0PFe6r6Nnn076OSWjltcr3r' },
        { 'icon': iconImage, 'title': '11 지구용사 우왁굳', 'file': 'https://docs.google.com/uc?id=1CLongRLjzPpalX-z8S8O08nS3GB5CaRQ' },
        { 'icon': iconImage, 'title': '12 별이 되지 않아도 돼', 'file': 'https://docs.google.com/uc?id=1Kaf8Tq8sBT2MEcKHx-8twHYAXvKQvsji' },
        { 'icon': iconImage, 'title': '13 학교괴담 ost - Grow u', 'file': 'https://docs.google.com/uc?id=10Bl1rLqM1du7Uf5GcAqFEJzupKAt7_uu' },
        { 'icon': iconImage, 'title': '14 DECO27 - モザイクロール(모자이크 롤)', 'file': 'https://docs.google.com/uc?id=1OyWf583ZvEvZVjDFS2kgJVREz9GCtvyS' },
        { 'icon': iconImage, 'title': '15 Always', 'file': 'https://docs.google.com/uc?id=17CxgfC11qqHn9lLqLrmCa4Hmun3KI3do' },
        { 'icon': iconImage, 'title': '16 팬서비스', 'file': 'https://docs.google.com/uc?id=1Hoi6x4z_kA75RaatW3zjRNfIL9RoRHwZ' },
        { 'icon': iconImage, 'title': '17 Strawberry moon', 'file': 'https://docs.google.com/uc?id=1ySF9mQbuNwLssC-Kb-GdE0oYiOxoRcmX' },
        { 'icon': iconImage, 'title': '18 사쿠란보', 'file': 'https://docs.google.com/uc?id=16uk6haBQIlfepgspF9r-wYWDpJQWQBr6' },
        { 'icon': iconImage, 'title': '19 후라이의 꿈', 'file': 'https://docs.google.com/uc?id=11oSy0AeJQzcvuQg1cALHND3m7ygaOwhb' },
        { 'icon': iconImage, 'title': '20 마루코는 아홉살ost', 'file': 'https://docs.google.com/uc?id=1FbCFKcEPWp2vXUbW1cqHE8FADm8H3utP' },
        { 'icon': iconImage, 'title': '21 솟구치는 투지', 'file': 'https://docs.google.com/uc?id=1y3VOhUfNYLl1rUQ3Qm7TsnRy5dBibuyl' },
        { 'icon': iconImage, 'title': '22', 'file': 'https://docs.google.com/uc?id=1zMiSj_HuSBUbtZAlFIlCZpNzckFqYtic' },
        { 'icon': iconImage, 'title': '고세구 - 출근송', 'file': 'https://docs.google.com/uc?id=1iDaWdkp5Wq6ieeC8mEXjGign_HUFH0EC' },
        { 'icon': iconImage, 'title': '김하온 - 붕붕', 'file': 'https://docs.google.com/uc?id=1070BrXnS86ychWHs9SGNsh25hNyOGKSc' },
        { 'icon': iconImage, 'title': '나 언젠간 떠날거야 (모아나 OST)', 'file': 'https://docs.google.com/uc?id=104eWotnIhdQDFQhthL3xjw3ihq9rjz3t' },
        { 'icon': iconImage, 'title': '내 손을 잡아 - 아이유', 'file': 'https://docs.google.com/uc?id=1jzICgIYPG3KLhzANUNCxfWhjTT6-3psO' },
        { 'icon': iconImage, 'title': '넬 - 기억을 걷는 시간', 'file': 'https://docs.google.com/uc?id=13BxIaOw2qNqxP3-wfRG7wRjZVf8XnK67' },
        { 'icon': iconImage, 'title': '데이먼스 이어 - Auburn', 'file': 'https://docs.google.com/uc?id=1IdEGuaDNPKTFaX24v_PAhngArh42SiFY' },
        { 'icon': iconImage, 'title': '땡벌 - 강진', 'file': 'https://docs.google.com/uc?id=1yAIwPUsc-NPskvvk18q_zTPV6VuK3M7G' },
        { 'icon': iconImage, 'title': '띵 (Prod.By 기리보이) - Jvcki Wai, 영비, Osshun Gum, 한요한', 'file': 'https://docs.google.com/uc?id=1iHHl7mKh1cRpTdPPwE_j-RSn8Tg70xH8' },
        { 'icon': iconImage, 'title': '루카루카 나이트피버', 'file': 'https://docs.google.com/uc?id=1vYPFdavXXDdGko3flMmQSaXfkuuzxAMG' },
        { 'icon': iconImage, 'title': '백예린 - 이럴거면 그러지 말지', 'file': 'https://docs.google.com/uc?id=10GF9kvjdENgv21WwEw1sD-i0WBSoY1pd' },
        { 'icon': iconImage, 'title': '별이 되지 않아도 돼 - 109', 'file': 'https://docs.google.com/uc?id=1sQ0wM1WXpiVmKH2gmoyvtKOV6Gca5xtT' },
        { 'icon': iconImage, 'title': '볼빨간사춘기 - 나의 사춘기에게', 'file': 'https://docs.google.com/uc?id=1mX0KKFwA9EBa8qwNjKO--v-Er-WFtkPq' },
        { 'icon': iconImage, 'title': '볼빨간사춘기 - 별 보러 갈래', 'file': 'https://docs.google.com/uc?id=1qH-OJvSuL4Ge651M76YOUBTp_eTmlxkt' },
        { 'icon': iconImage, 'title': '볼빨간사춘기 - 우주를 줄게', 'file': 'https://docs.google.com/uc?id=1JsoAKlYob0b2mwmikoiM9Khx09Nhy7Uz' },
        { 'icon': iconImage, 'title': '볼빨간사춘기 - 워커홀릭', 'file': 'https://docs.google.com/uc?id=1LUvVXwTfG0LZnLfDLDMjMasBuv4OhSNn' },
        { 'icon': iconImage, 'title': '부엉이 - 코키아', 'file': 'https://docs.google.com/uc?id=1L4-rd9A64lLaF0XqqjgE5RReBbFB4RAb' },
        { 'icon': iconImage, 'title': '선우정아 - 고양이', 'file': 'https://docs.google.com/uc?id=1Vvv3h3E7KLMGBB36Fb_6STPuTpjd-h8g' },
        { 'icon': iconImage, 'title': '아모르파티 - 김연자', 'file': 'https://docs.google.com/uc?id=1c6tgkTzYFSS12idcGmk25FV7-dToCX-r' },
        { 'icon': iconImage, 'title': '아이유 - 가을아침', 'file': 'https://docs.google.com/uc?id=10ivmf3_zDue37VpEYrfxUUpO0FsTxEen' },
        { 'icon': iconImage, 'title': '아이유 - 이지금', 'file': 'https://docs.google.com/uc?id=10JWvXXxSh-pGx6nJppX_v4o2UmMAN6Rg' },
        { 'icon': iconImage, 'title': '아이유 - Coin', 'file': 'https://docs.google.com/uc?id=1M8PJeP60oHiJvFqXZhMvKczXHAX_gsRN' },
        { 'icon': iconImage, 'title': '아이유 - Rain Dro', 'file': 'https://docs.google.com/uc?id=1TcnBXkdRNUAa4Y8MOGl0nFykoWQ9n0Qz' },
        { 'icon': iconImage, 'title': '악동뮤지션 - 낙하', 'file': 'https://docs.google.com/uc?id=1zhEpe1LeWNWg010ecyxydAQGKA6mGMoG' },
        { 'icon': iconImage, 'title': '악동뮤지션 - 시간과 낙엽', 'file': 'https://docs.google.com/uc?id=1afPXTq3iz_kLkfEmWfaV00wSFtVEPWYB' },
        { 'icon': iconImage, 'title': '악동뮤지션 - 이떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 'file': 'https://docs.google.com/uc?id=12BqV7zvmSzB5M88UOqEOhvxRvfrNL5g7' },
        { 'icon': iconImage, 'title': '악동뮤지션 - Dinosaur', 'file': 'https://docs.google.com/uc?id=1rXNGADSjRm1RANwUVJ4tp5X7yb8Nl5G8' },
        
    ]
});