
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '데스노트', 'file': 'https://docs.google.com/uc?id=1TOwW00PxsWJKYV02c2If2rhvHQDt-8LA' },
        { 'icon': iconImage, 'title': '러브크로니클', 'file': 'https://docs.google.com/uc?id=15ty3KfQBT-UXB24gKV4TyQWSxDKNdXBF' },
        { 'icon': iconImage, 'title': '마리골드', 'file': 'https://docs.google.com/uc?id=1pBH7FOfnpEVhaWpnpUpqzIdRzf6vBEAz' },
        { 'icon': iconImage, 'title': '목마름을 외치다', 'file': 'https://docs.google.com/uc?id=1xVH-aO6_JGDcesqKjDylO_z1D4hiVGyP' },
        { 'icon': iconImage, 'title': '변하지않는것', 'file': 'https://docs.google.com/uc?id=1osQwGKpWqLETx4FqJ39iKDgM2m17tJ0i' },
        { 'icon': iconImage, 'title': '불꽃', 'file': 'https://docs.google.com/uc?id=1MHascOAeHfgrA2Wf7IeRSERGixS_-nEW' },
        { 'icon': iconImage, 'title': '사랑의구조신호', 'file': 'https://docs.google.com/uc?id=1hGW82aHDHsWaqzz2h_6njWFAnWUWYuMh' },
        { 'icon': iconImage, 'title': '연애재판', 'file': 'https://docs.google.com/uc?id=1PdzRkFTixIwSAvEcwRD-gRwbBbZl2SXx' },
        { 'icon': iconImage, 'title': '요구르팅', 'file': 'https://docs.google.com/uc?id=176s0uC8gDGMD1y8FZoeU2cPhi0mr-KRS' },
        { 'icon': iconImage, 'title': '이별만이 인생이다', 'file': 'https://docs.google.com/uc?id=1olvmuzDajpyHrhAEHxPg9OkaRIuuZZ8O' },
        { 'icon': iconImage, 'title': '초침을깨물다', 'file': 'https://docs.google.com/uc?id=1y229Na38QBJsN2rfBBn2DISEMwjQgeAm' },
        { 'icon': iconImage, 'title': '코이', 'file': 'https://docs.google.com/uc?id=1wDYdxyKS84BVz94747ldsKtHJiE7MSWi' },
        { 'icon': iconImage, 'title': '호랑수월가', 'file': 'https://docs.google.com/uc?id=1GcVWPeqj6rqWO4nQB9IMSGKvYiiN25pY' },
        { 'icon': iconImage, 'title': 'Lovingyou시간을넘어서', 'file': 'https://docs.google.com/uc?id=1byxxnvqXBEU7KUHnX6VAHpWDBr8laXVd' },
        { 'icon': iconImage, 'title': 'NewFuture', 'file': 'https://docs.google.com/uc?id=1ztHVv2aSoQfUW89jZCe40E-s230fRBYk' },
        { 'icon': iconImage, 'title': 'Again(강철의 연금술사OST)', 'file': 'https://docs.google.com/uc?id=1kyZszX2bH2hJt9PiZ1p2tkpdJp6KSpVW' },
        { 'icon': iconImage, 'title': 'Bang Bang', 'file': 'https://docs.google.com/uc?id=19J3MxKOWcsB8XnTTHN3rs3cE39FpFZse' },
        { 'icon': iconImage, 'title': 'Beautiful World(에반게리온OST)', 'file': 'https://docs.google.com/uc?id=1s9n8ujc9BvktR0rXRjLzGb2f3P1jmeos' },
        { 'icon': iconImage, 'title': 'Believer', 'file': 'https://docs.google.com/uc?id=162FkhTbt6NvZh8fOGrcWBajSI0pyB0O6' },
        { 'icon': iconImage, 'title': 'Closer', 'file': 'https://docs.google.com/uc?id=13nZysRSvQObVpUecMTUfvTBb3F3S6otT' },
        { 'icon': iconImage, 'title': 'Cups(Pitch Perfect OST)', 'file': 'https://docs.google.com/uc?id=149WLnDMeJjJJV2Tna34PVOf4yUyZxmhP' },
        { 'icon': iconImage, 'title': 'Dance Monkey', 'file': 'https://docs.google.com/uc?id=1W7ZZAu43j9gdN_7SA_mfC_S1nIUBx639' },
        { 'icon': iconImage, 'title': 'Daze(메카쿠시티 액터즈 OST)고화질', 'file': 'https://docs.google.com/uc?id=1f3u4qpeWv49Y7UFMyEWIUg6b4jw3Rhym' },
        { 'icon': iconImage, 'title': 'Do It For Her (스티븐 유니버스 OST)', 'file': 'https://docs.google.com/uc?id=1tqAjcIDjAUiQMXVN_sf56rv_8Lz_7oli' },
        { 'icon': iconImage, 'title': 'Enemy(아케인OST)', 'file': 'https://docs.google.com/uc?id=18db_5uE16tgfOs1l7-Acp13WFv0A9JIX' },
        { 'icon': iconImage, 'title': 'Everything Stays (어드벤쳐 타임 OST)', 'file': 'https://docs.google.com/uc?id=1gChkHwL4gk59ZCwlB9PBahE55D7WAVRP' },
        { 'icon': iconImage, 'title': 'For You (나루토 OST)', 'file': 'https://docs.google.com/uc?id=1jdFp8ZNbr1ifQ6XbuWxar-gcw4_IGojy' },
        { 'icon': iconImage, 'title': 'Fruits Basket OP', 'file': 'https://docs.google.com/uc?id=1MQluZnDz8nEWvIYbivYxY2j8_9CkdwW8' },
        { 'icon': iconImage, 'title': 'Fry Song(어드벤쳐 타임 OST)', 'file': 'https://docs.google.com/uc?id=1aALF6yu-44axTTUvULMTjHnlfOucp0rc' },
        { 'icon': iconImage, 'title': 'Get music! (프리즘스톤-올스타셀렉션OST)', 'file': 'https://docs.google.com/uc?id=1q2_yEM9hCVkLAPWHe1AcVlJ1v847VT2x' },
        { 'icon': iconImage, 'title': 'Glow', 'file': 'https://docs.google.com/uc?id=13dVSqp2bMouf_VP1x7UXQCZJuABr7aDF' },
        { 'icon': iconImage, 'title': 'Havana', 'file': 'https://docs.google.com/uc?id=1R1wUvagATZNyrIgTQXE9aFjCMpvDodH3' },
        { 'icon': iconImage, 'title': 'Here Comes a Thought', 'file': 'https://docs.google.com/uc?id=1sMa7SVp4ZkGcyOZq348u9LWIJaUqgTJb' },
        { 'icon': iconImage, 'title': 'Here(마법사의 신부OST)', 'file': 'https://docs.google.com/uc?id=10KZU-GqHsglHnv-LxQz9m443vdcugqWK' },
        { 'icon': iconImage, 'title': 'I am Stronger Than You(스티븐 유니버스 OST)', 'file': 'https://docs.google.com/uc?id=1XHzvC9b_xNLnxQGQpSbG4i-L7BpTzUGS' },
        { 'icon': iconImage, 'title': 'I\'m Just Your Proble', 'file': 'https://docs.google.com/uc?id=1vAtsMwQhkzZejWilpJd9lu69ZbXmmhq-' },
        { 'icon': iconImage, 'title': 'If I Had Wings', 'file': 'https://docs.google.com/uc?id=1sdjxl3nXVRWloWE5YlvhI1nkbo43Ei_o' },
        { 'icon': iconImage, 'title': 'It\'s Over, Isn\'t It (스티븐 유니버스 OST)', 'file': 'https://docs.google.com/uc?id=1_MNU2xfqijp2csFd9CGXp8fOY795zkkE' },
        { 'icon': iconImage, 'title': 'Jump Up, Super Star(슈퍼마리오 오딧세이 삽입곡)', 'file': 'https://docs.google.com/uc?id=1yjD-mhYynNFjV03WvNCX1ukuG8LF6UtT' },
        { 'icon': iconImage, 'title': 'LengendsNeverDie', 'file': 'https://docs.google.com/uc?id=1tZeBMtUP_k3M9B5wzlpvYflPJHOrPoFj' },
        { 'icon': iconImage, 'title': 'Let It Out(강철의 연금술사 OST)', 'file': 'https://docs.google.com/uc?id=16s2oM88nDJhD9hcf7rCp5ms-wLgBOXaJ' },
        { 'icon': iconImage, 'title': 'Lion(마크로스F OST)', 'file': 'https://docs.google.com/uc?id=1DlQk34HDDbgCpClFKOxzcFdg3_4nd0c8' },
        { 'icon': iconImage, 'title': 'Love Like You(스티븐 유니버스 OST)', 'file': 'https://docs.google.com/uc?id=1aOtGTemudsiIYDx7NFQrObkAilI6W6k9' },
        { 'icon': iconImage, 'title': 'lovely', 'file': 'https://docs.google.com/uc?id=18P8Xn1qi9-jFJ2IJndSV3vXkUCinFjSj' },
        { 'icon': iconImage, 'title': 'My Heart Will Go On(타이타닉OST)', 'file': 'https://docs.google.com/uc?id=1_Ey3JxMjAaYkS0VjbCeN81FCuHT9mnrz' },
        { 'icon': iconImage, 'title': '꼭두각시 피에로', 'file': 'https://docs.google.com/uc?id=1m3DYxzjbuH6rTW-zbv4ldN_h_pXRW3jM' },
        { 'icon': iconImage, 'title': '네가 아니면 안될 것 같아(월간 순정 노자키쿤 OST)', 'file': 'https://docs.google.com/uc?id=1DndlUiPDkOmg1r2Ba1IEc-Gxi2mcuzS1' },
        { 'icon': iconImage, 'title': '도넛홀', 'file': 'https://docs.google.com/uc?id=15ud3uzEDLoML0c0O70xteDMJtJKYrmA5' },
        { 'icon': iconImage, 'title': '레베카', 'file': 'https://docs.google.com/uc?id=15Mv2hNb-k_C4SvSTzVMa-QnHqOjLleDk' },
        { 'icon': iconImage, 'title': '모자이크 롤', 'file': 'https://docs.google.com/uc?id=1ph4ce70yArOxrdNoFwjbarT3L62by8C4' },
        { 'icon': iconImage, 'title': '목마름을 외치다(도메스틱한 그녀OST)', 'file': 'https://docs.google.com/uc?id=1gsXYf6GN-Y14zGpujKN-pC8P-yEpetvL' },
        { 'icon': iconImage, 'title': '무지개색 곰곰(마크로스F OST)고', 'file': 'https://docs.google.com/uc?id=1CNMk55DRflCFucAuzH6LM_GyPoSAMRIX' },
        { 'icon': iconImage, 'title': '반짝반짝 치카치카', 'file': 'https://docs.google.com/uc?id=1oqPMn7Ecc-IBpHT6eim68bH_x6N7Adqq' },
        { 'icon': iconImage, 'title': '사용설명서', 'file': 'https://docs.google.com/uc?id=1Wn5FUVMQ1A7Xk6Gk1Xm-XpEObmWL27Cg' },
        { 'icon': iconImage, 'title': '슈가송과 비터스텝(혈계전선OST)', 'file': 'https://docs.google.com/uc?id=1eyA-qyHVaVyzi5wjpdOnln0MmYSqJHiP' },
        { 'icon': iconImage, 'title': '약속의 씨앗', 'file': 'https://docs.google.com/uc?id=1cJsmDjzlv06R9-BO9l12rGB6xlcNzZ5b' },
        { 'icon': iconImage, 'title': '오버마스터(아이돌마스터 밀리시타)', 'file': 'https://docs.google.com/uc?id=1n8L3viHhJYbTBNvUkiI-qaqit_04NSBR' },
        { 'icon': iconImage, 'title': '월량대표아적심', 'file': 'https://docs.google.com/uc?id=1lN5x42PBxQTk8JAnZhV3U3JhdbaleB5K' },
        { 'icon': iconImage, 'title': '이름없는노래', 'file': 'https://docs.google.com/uc?id=1qGtkqPxZ3toKIfkke55nBmRVn2RkMTaB' },
        { 'icon': iconImage, 'title': '잊혀지지 않는 말(모바일게임 Grimms Notes OST)', 'file': 'https://docs.google.com/uc?id=1QCeL1tXkVVautlZ896GA4LG7gJXkpTyv' },
        { 'icon': iconImage, 'title': '재능샘플러', 'file': 'https://docs.google.com/uc?id=1OT_SeoF8iTvnAyP7m00mrLJYcqFVwK6s' },
        { 'icon': iconImage, 'title': '편익의새(괭이갈매기 울적에OP)', 'file': 'https://docs.google.com/uc?id=1FKnEb9uvFvlA3Y6aDoR525_Dizysmzv3' },
        { 'icon': iconImage, 'title': '황금별', 'file': 'https://docs.google.com/uc?id=1M8Lv21Ovj6hSx-wZWoTFVCNCYcdStmoP' },
        { 'icon': iconImage, 'title': 'My Heart Will Go On(타이타닉OST)2', 'file': 'https://docs.google.com/uc?id=1a5mQ9QaPRRnD0itxtSXGS1BbG8UPhBDh' },
        { 'icon': iconImage, 'title': 'Myself(달빛천사OST)', 'file': 'https://docs.google.com/uc?id=1yJC6zphjEDTflLGvi6pN1zFW_b4DCfm8' },
        { 'icon': iconImage, 'title': 'Orange', 'file': 'https://docs.google.com/uc?id=1oNMCsDaOoKouxS-7fzQxFl021tzqVmC3' },
        { 'icon': iconImage, 'title': 'Q&A 리사이클 (옆자리 괴물군 OST)', 'file': 'https://docs.google.com/uc?id=1eMM4yr9hhTGONf86IS6gjdD77c1y0giT' },
        { 'icon': iconImage, 'title': 'Royals', 'file': 'https://docs.google.com/uc?id=1yvTa-1TIyLgs7m8BlPvCDrv4Axr2BaFQ' },
        { 'icon': iconImage, 'title': 'Scarborough Fair', 'file': 'https://docs.google.com/uc?id=101DVLrmv_lZukNhKdObg07KqSDQn06rZ' },
        { 'icon': iconImage, 'title': 'Someone Like You', 'file': 'https://docs.google.com/uc?id=1G0afXfRDDUF1VInO8rbBNG-dvGFSmqgF' },
        { 'icon': iconImage, 'title': 'Stronger', 'file': 'https://docs.google.com/uc?id=1xWPSBfSVtfW0e_09vZ4K2fxIfNV7TDnl' },
        { 'icon': iconImage, 'title': 'Tik Tok', 'file': 'https://docs.google.com/uc?id=1kd0Ayw-d6nkqXM_ul0Fqee2pgcdMYOKV' },
        { 'icon': iconImage, 'title': 'Toxic', 'file': 'https://docs.google.com/uc?id=1bZ2WYZ6CwSWew2eYx_nNkpn39XBXQ-4m' },
        { 'icon': iconImage, 'title': 'Wrecking Ball', 'file': 'https://docs.google.com/uc?id=1X5ZwBnnVOOEoA-NBZD420baHxKnQKWtu' },
        { 'icon': iconImage, 'title': '겨울왕국 - For the first time in forever', 'file': 'https://docs.google.com/uc?id=1rMQk0Mvfl5i7kTPlnq_UGr4n7MOZ-V60' },
        { 'icon': iconImage, 'title': '내가 죽으려 생각한 것은', 'file': 'https://docs.google.com/uc?id=10BmYmr9rD83LX60AeYI4m6hRcvfBsJWg' },
        { 'icon': iconImage, 'title': '라푼젤 - when will my life begin', 'file': 'https://docs.google.com/uc?id=18jFfFgqcnQ_Ez_RWyRzyGLE0wjIGjxYi' },
        { 'icon': iconImage, 'title': '러브 크로니클', 'file': 'https://docs.google.com/uc?id=1AXpHkUlufopV90U8jZtEaqwpjz9eIw8v' },
        { 'icon': iconImage, 'title': '밤편지', 'file': 'https://docs.google.com/uc?id=1nwEA3X5Gc5APXhx5uv4gvI3d61HZ75Sm' },
        { 'icon': iconImage, 'title': '성간비행', 'file': 'https://docs.google.com/uc?id=1jQOaesefmjKz4NwcJrZ2KTobbeHQD4-H' },
        { 'icon': iconImage, 'title': '아이유 비밀의정원', 'file': 'https://docs.google.com/uc?id=108wfDruBqu-R86cmyPVeyl496mrTkyYK' },
        { 'icon': iconImage, 'title': '아이유 이지금', 'file': 'https://docs.google.com/uc?id=11RoQWdCvmS8aA9YYo3imtcSuZnLztZ4l' },
        { 'icon': iconImage, 'title': '어푸', 'file': 'https://docs.google.com/uc?id=1DLQIktFNSn6VUNOXztT_jprgcSY3kB0Z' },
        { 'icon': iconImage, 'title': '여우비', 'file': 'https://docs.google.com/uc?id=1GGWFXoQukHWw0HOsEqwljFZLf9XMEzVR' },
        { 'icon': iconImage, 'title': '인어공주 - part of your world', 'file': 'https://docs.google.com/uc?id=1YuET2tKZOI0NCg9AdiXLiUwPX-24iDkF' },
        { 'icon': iconImage, 'title': '일루저니스타', 'file': 'https://docs.google.com/uc?id=1t1-Ch0BUdyAq-lQ18aK5lIXQkRn64NSW' },
        { 'icon': iconImage, 'title': '화조도', 'file': 'https://docs.google.com/uc?id=1lWBCJDnmD9AUfQYGeUtxE2EKOlZs1ku_' },
        { 'icon': iconImage, 'title': 'Bing Crosby - White chrismas', 'file': 'https://docs.google.com/uc?id=1n_Jo2cAEqKO1LsoOHrlL3pNnmOrGCb8f' },
        { 'icon': iconImage, 'title': 'it_s over isn_t it', 'file': 'https://docs.google.com/uc?id=1knIzIFdfm_4hzZbnX9JGc_sdzeFC0fZq' },
        { 'icon': iconImage, 'title': 'Popular', 'file': 'https://docs.google.com/uc?id=1dtaARDNrX3G2pN07wfgU4ggmE5HeEJdB' },
        { 'icon': iconImage, 'title': 'remember me', 'file': 'https://docs.google.com/uc?id=16MF-Kowxa9iCDQozLGzyaCH5I51l7gLR' },
        { 'icon': iconImage, 'title': 'Sia - snow man', 'file': 'https://docs.google.com/uc?id=1gmhySRj8i5_bgVh470rkx7Sd659wOqPb' },
        { 'icon': iconImage, 'title': '아라리', 'file': 'https://docs.google.com/uc?id=1qPoZ09QtLQ57pMrvbwJp1QbFCuvOaazY' },
        { 'icon': iconImage, 'title': '트와이스 - Fancy', 'file': 'https://docs.google.com/uc?id=1Wio3oT4h3kiX9eNYdUsHjfJz00kuS3k1' },
        { 'icon': iconImage, 'title': 'don_t you worry about a thing', 'file': 'https://docs.google.com/uc?id=1pRFZi80Q8244-IBhOiuuR3XTkt5ZaYMQ' },
                        
    ]
});