
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '꼭두각시 피에로', 'file': 'https://docs.google.com/uc?id=1oOW1qw-3efrwiTN5BUuS5Salb1AtE75G' },
        { 'icon': iconImage, 'title': '나카시마미카-내가죽으려생각한것은', 'file': 'https://docs.google.com/uc?id=1bqS11N7cB6fM5s91NFxkfaU0ClEyciI8' },
        { 'icon': iconImage, 'title': '네가 아니면 안될 것 같아(월간 순정 노자키쿤 OST)', 'file': 'https://docs.google.com/uc?id=19K9fVau4IW5JqgrRzfhMqCmvENqdRcvA' },
        { 'icon': iconImage, 'title': '데스노트', 'file': 'https://docs.google.com/uc?id=1z9bEE79T7ADn4wLVxKgwA3AHn19rQ6NL' },
        { 'icon': iconImage, 'title': '도넛홀', 'file': 'https://docs.google.com/uc?id=1IJ5JgAbifRg9PgEa07esKUI1lzi7r-6G' },
        { 'icon': iconImage, 'title': '란카 리-성간비행', 'file': 'https://docs.google.com/uc?id=1vCRx3kMoRU0_7Yf2Kd18jdvgz7dYJpJF' },
        { 'icon': iconImage, 'title': '러브크로니클', 'file': 'https://docs.google.com/uc?id=1RDap_Zcu6ohayIaWx4JyNp3seV733RrY' },
        { 'icon': iconImage, 'title': '레베카', 'file': 'https://docs.google.com/uc?id=1j4ZqJkmnitRT2Wsz6fZg9mxGtm-APVgT' },
        { 'icon': iconImage, 'title': '마리골드', 'file': 'https://docs.google.com/uc?id=1bdahL4gfYnr_owdC2audM8Tjsx2lNaKb' },
        { 'icon': iconImage, 'title': '모자이크 롤', 'file': 'https://docs.google.com/uc?id=183Gx_ZDPkcIeXh93eNZ6Kd7qNnxLuG_T' },
        { 'icon': iconImage, 'title': '목마름을 외치다', 'file': 'https://docs.google.com/uc?id=16LQVnBgBKGTlev4LUtyug52jjg5VS9FM' },
        { 'icon': iconImage, 'title': '목마름을 외치다(도메스틱한 그녀OST)', 'file': 'https://docs.google.com/uc?id=1vSjjcEbTTCq3Kq7HStptITG064m6ObAp' },
        { 'icon': iconImage, 'title': '무지개색 곰곰(마크로스F OST)고', 'file': 'https://docs.google.com/uc?id=1G9BuDmFeLe_TeC_LrsVeYiSxuo8w7aR2' },
        { 'icon': iconImage, 'title': '반짝반짝 치카치카', 'file': 'https://docs.google.com/uc?id=1sTzD_Yh48A6n7HrjlwzlVvxpYOgRjyXv' },
        { 'icon': iconImage, 'title': '변하지않는것', 'file': 'https://docs.google.com/uc?id=13yEUW-BKPC0vucKPrermI_QS5YPuxlIj' },
        { 'icon': iconImage, 'title': '불꽃', 'file': 'https://docs.google.com/uc?id=1IXFosWoBVAubeTifzIjaTZ7ebCeq9ee0' },
        { 'icon': iconImage, 'title': '사랑의구조신호', 'file': 'https://docs.google.com/uc?id=1VbdnOuP2uC1cTd1p8fwIjiUde_0NlmTs' },
        { 'icon': iconImage, 'title': '사용설명서', 'file': 'https://docs.google.com/uc?id=1f-4xSdwgL4frO5vl6Yv_US2PHQ9XhG5v' },
        { 'icon': iconImage, 'title': '슈가송과 비터스텝(혈계전선OST)', 'file': 'https://docs.google.com/uc?id=1kFcUZmpyLUF7qV2Wrx2Erp6_aE903krd' },
        { 'icon': iconImage, 'title': '심규선 - 아라리', 'file': 'https://docs.google.com/uc?id=1GHOM1H_Y_j8KwoNcj4J1yoVMzmGbsPAj' },
        { 'icon': iconImage, 'title': '심규선-화조도', 'file': 'https://docs.google.com/uc?id=1ubq8JHdyb41fnTEHJWY7sMROP0xzPGmF' },
        { 'icon': iconImage, 'title': '약속의 씨앗', 'file': 'https://docs.google.com/uc?id=1IgbCy26c4Vu2DfhJuxzlMAEPtFxAzp3w' },
        { 'icon': iconImage, 'title': '연애재판', 'file': 'https://docs.google.com/uc?id=1Q0NJHVqcy16gvmHVZPgLJIoG8-FKiO_u' },
        { 'icon': iconImage, 'title': '오버마스터(아이돌마스터 밀리시타)', 'file': 'https://docs.google.com/uc?id=1N-SPYXu_ybVD-6k7t58lKZ_ylu2pe9tQ' },
        { 'icon': iconImage, 'title': '요구르팅', 'file': 'https://docs.google.com/uc?id=1EPrDDIbUp7PZnIEqJtF-zY_r8BbgciFN' },
        { 'icon': iconImage, 'title': '월량대표아적심', 'file': 'https://docs.google.com/uc?id=13e17tigSUMOXRt6D3JHq_6AnQAhGf7HD' },
        { 'icon': iconImage, 'title': '이름없는노래', 'file': 'https://docs.google.com/uc?id=1daEcPNBxE8SnAl-OGxUkF8wF2tE8e8_G' },
        { 'icon': iconImage, 'title': '이별만이 인생이다', 'file': 'https://docs.google.com/uc?id=1qEZmXbqP8nGDL0-N3-tPaAZvqA4jbXZA' },
        { 'icon': iconImage, 'title': '이선희-여우비', 'file': 'https://docs.google.com/uc?id=1EB0CT9gFmcyAR87_BvvmdbjoAzaMCv6q' },
        { 'icon': iconImage, 'title': '일루저니스타!', 'file': 'https://docs.google.com/uc?id=1plYxP-BWHN7uQlYMI5gQd4T5MOSNFW1u' },
        { 'icon': iconImage, 'title': '잊혀지지 않는 말(모바일게임 Grimms Notes OST)', 'file': 'https://docs.google.com/uc?id=1tynnbKoabWEmSIpYWbfwemEcawR9tjyI' },
        { 'icon': iconImage, 'title': '재능샘플러', 'file': 'https://docs.google.com/uc?id=1D-VL8bPpnko3rXmFyOSejA2m71n2d6Br' },
        { 'icon': iconImage, 'title': '초침을깨물다', 'file': 'https://docs.google.com/uc?id=1TdAIzyJosgXlAs2MqDR-C85obXvlTTcs' },
        { 'icon': iconImage, 'title': '코이', 'file': 'https://docs.google.com/uc?id=1HN0HI8NjrH0sRAbjHiin69p6u5ZYlYQu' },
        { 'icon': iconImage, 'title': '편익의새(괭이갈매기 울적에OP)', 'file': 'https://docs.google.com/uc?id=1KQIuG8Wns7SAmjYqCrvKTsvtkBOnLwnm' },
        { 'icon': iconImage, 'title': '호랑수월가', 'file': 'https://docs.google.com/uc?id=1m10AGY9kafH6c174EA_bVNPtMu0PfWXE' },
        { 'icon': iconImage, 'title': '황금별', 'file': 'https://docs.google.com/uc?id=1fXXdsg7IQMPQlGXUQDZupPkXJi1x6QlL' },
        { 'icon': iconImage, 'title': 'Again(강철의 연금술사OST)', 'file': 'https://docs.google.com/uc?id=1JkGOSzaj2OspZIWEkgkCHuzqcN4rL6C0' },
        { 'icon': iconImage, 'title': 'Bang Bang', 'file': 'https://docs.google.com/uc?id=13EB_NQCX0z1P30BFt0E3bBsu0jlUYCRq' },
        { 'icon': iconImage, 'title': 'Beautiful World(에반게리온OST)', 'file': 'https://docs.google.com/uc?id=124zOaETwryFxlM3g34rwtv7Jlz0Y9_i1' },
        { 'icon': iconImage, 'title': 'Believer', 'file': 'https://docs.google.com/uc?id=1F_OOSaf_tjQyPiDkZcNSYqEkRdLEeFu-' },
        { 'icon': iconImage, 'title': 'Closer', 'file': 'https://docs.google.com/uc?id=1qzQCxBxSV_qJPHwkFmbJBKRwGVmCaprz' },
        { 'icon': iconImage, 'title': 'Cups(Pitch Perfect OST)', 'file': 'https://docs.google.com/uc?id=1oTMKdE-jyQdL-sgyfvgqqIXFCsHDRssx' },
        { 'icon': iconImage, 'title': 'Dance Monkey', 'file': 'https://docs.google.com/uc?id=11ODWZKGW7544URIEAVeCyRvgN8V_SfpN' },
        { 'icon': iconImage, 'title': 'Daze(메카쿠시티 액터즈 OST)고화질', 'file': 'https://docs.google.com/uc?id=1Nnnp3usDO8ujNND2FfIb2jijDE_V4Sf2' },
        { 'icon': iconImage, 'title': 'Do It For Her (스티븐 유니버스 OST)', 'file': 'https://docs.google.com/uc?id=1y_8KQx00ZPkSIPVnBqazflQo1NWxeiI_' },
        { 'icon': iconImage, 'title': 'Enemy(아케인OST)', 'file': 'https://docs.google.com/uc?id=1Vhjycagyb67qfa95bzx6EsGfcgzuc69I' },
        { 'icon': iconImage, 'title': 'Everything Stays (어드벤쳐 타임 OST)', 'file': 'https://docs.google.com/uc?id=1TdyKe59Qv_2YJMFdn53jsjYceCVdHpXT' },
        { 'icon': iconImage, 'title': 'For You (나루토 OST)', 'file': 'https://docs.google.com/uc?id=19neK7-dJ4WoF7fNA9gkE1usgraVLuoAg' },
        { 'icon': iconImage, 'title': 'FortheFirstTimeinForever', 'file': 'https://docs.google.com/uc?id=1JKovCmwEoVofFgK7Ueel7IuiRxRCSI9j' },
    ]
});