
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '17171771', 'file': 'https://docs.google.com/uc?id=1PuEBDXPtiAbu-nuifKYOQt0mhWHGMvNG' },
        { 'icon': iconImage, 'title': '가까이 하고 싶은 그대', 'file': 'https://docs.google.com/uc?id=1xx5PipP7JFxxtbaymNNIhFQmKaNDQcUJ' },
        { 'icon': iconImage, 'title': '가질 수 없는 너', 'file': 'https://docs.google.com/uc?id=11UrlrP51SN5iCUDF_088uB3Tvq55KshI' },
        { 'icon': iconImage, 'title': '고속도로 Romance', 'file': 'https://docs.google.com/uc?id=1Gxgktyqv5xAF5VcZwHK6kWGS-THKEF-M' },
        { 'icon': iconImage, 'title': '그대라는 사치', 'file': 'https://docs.google.com/uc?id=1h4XsCh-2PzYqKV1HGfFeNskTiB_Q9jJQ' },
        { 'icon': iconImage, 'title': '그대만 있다면', 'file': 'https://docs.google.com/uc?id=1SbXFsBI6_7aBVEUJfiJDaMf9TyGtAdJE' },
        { 'icon': iconImage, 'title': '그래도 나 사랑하지', 'file': 'https://docs.google.com/uc?id=13tYyTzfqH0fp53QkxetNmnzZvbY93wV0' },
        { 'icon': iconImage, 'title': '금요일에 만나요', 'file': 'https://docs.google.com/uc?id=1b9sAva0LM2pOw0W-JRpLjyMExBOQJAI0' },
        { 'icon': iconImage, 'title': '나를 너에게', 'file': 'https://docs.google.com/uc?id=15h49Yyd113LmI9-DCwNXPOZvaXRBKoG4' },
        { 'icon': iconImage, 'title': '나를 슬프게 하는 사람들', 'file': 'https://docs.google.com/uc?id=13UrziVvVdGpfxO6REvHMv5SvDAz147cc' },
        { 'icon': iconImage, 'title': '나만 안되는 연애', 'file': 'https://docs.google.com/uc?id=1C86MQPjHIAsQgkLhOTDKQaWzLNGsVAPw' },
        { 'icon': iconImage, 'title': '낭만고양이', 'file': 'https://docs.google.com/uc?id=12SbWjiFL3Fk8Qyrkl-3GtUvbtIZbafET' },
        { 'icon': iconImage, 'title': '내 손을 잡아', 'file': 'https://docs.google.com/uc?id=13sm76EIKFltKD8OsWSMqLkFYFSbrXJl0' },
        { 'icon': iconImage, 'title': '내꺼야', 'file': 'https://docs.google.com/uc?id=1GDvVZNWCRf5DoqCX6NVnRBKumVGSUOE2' },
        { 'icon': iconImage, 'title': '너는 내 남자', 'file': 'https://docs.google.com/uc?id=1vov2SZ6MIf5pjZTqgzib_eAKrte-M1Xr' },
        { 'icon': iconImage, 'title': '너랑 나', 'file': 'https://docs.google.com/uc?id=16KCDGOkUKyPAOr84k_ayPF7_juEEiqOi' },
        { 'icon': iconImage, 'title': '너의 의미', 'file': 'https://docs.google.com/uc?id=1Vpq6zgeZ0Oio0m7vzKz7oYt3MBWWv9KD' },
        { 'icon': iconImage, 'title': '달리기', 'file': 'https://docs.google.com/uc?id=1g8iCkRxh-i-Zg5CUOY0BIrmqGKUv4ocS' },
        { 'icon': iconImage, 'title': '답답한 새벽', 'file': 'https://docs.google.com/uc?id=1aLMB8IjSiRkqLDzcMdMAghtmJbxAZ1os' },
        { 'icon': iconImage, 'title': '두근두근', 'file': 'https://docs.google.com/uc?id=1W8zuXy5eWt8sfxVhSQ9ocOyq5baLqk0_' },
        { 'icon': iconImage, 'title': '말도 안돼 (개인의 취향 OST)', 'file': 'https://docs.google.com/uc?id=15xYS2fUCZp1kL9mWby0chMhpNANZmniN' },
        { 'icon': iconImage, 'title': '무릎', 'file': 'https://docs.google.com/uc?id=1lwbQE-E2e6TQ71j-7Pe8to6JKfU1pKh-' },
        { 'icon': iconImage, 'title': '밤편지', 'file': 'https://docs.google.com/uc?id=1fTzsqtnBG3HkJy8uLp5TfTpfAXaXL2gB' },
        { 'icon': iconImage, 'title': '복숭아', 'file': 'https://docs.google.com/uc?id=11ao8sOj56k_npvcBKSM0qA1Wr9HkKArH' },
        { 'icon': iconImage, 'title': '불장난', 'file': 'https://docs.google.com/uc?id=1f8O4iUJqoW1bMIAfZ2VyNIMEwdI3clko' },
        { 'icon': iconImage, 'title': '삐딱하게', 'file': 'https://docs.google.com/uc?id=1cI1fxrWNF-HTp3xmQUE5FA-Yp8fOp01F' },
        { 'icon': iconImage, 'title': '사랑한다는 흔한 말', 'file': 'https://docs.google.com/uc?id=1AN7oYF78fM-3AFiYJBw_bvTNX_pe-2ZB' },
        { 'icon': iconImage, 'title': '사이렌 Remix', 'file': 'https://docs.google.com/uc?id=1XWPQ91k4_yZ71x01brcjI4Vm6QxgPxJA' },
        { 'icon': iconImage, 'title': '삭제', 'file': 'https://docs.google.com/uc?id=1vS6y9paQ4CxHyqbCJUb7lFTVUiTs9qt5' },
        { 'icon': iconImage, 'title': '삼촌', 'file': 'https://docs.google.com/uc?id=14RgDc8CNfjKDLRG958IpizLsakNmLJyU' },
        { 'icon': iconImage, 'title': '상상더하기', 'file': 'https://docs.google.com/uc?id=1d1tuzvInrGFbFDnsV6mXcCj3GaMuHqL8' },
        { 'icon': iconImage, 'title': '서시', 'file': 'https://docs.google.com/uc?id=1dl4a9CN45X3Qgf5cxfdSRy1D6HcWsYzo' },
        { 'icon': iconImage, 'title': '수고했어 오늘도', 'file': 'https://docs.google.com/uc?id=1T4b5q8q0ds7phwyZkeqsSXrz4i1jH7Dz' },
        { 'icon': iconImage, 'title': '시간아 천천히', 'file': 'https://docs.google.com/uc?id=1o1ptc9SYtVjs21kTDv1rdPw1TWDWfG14' },
        { 'icon': iconImage, 'title': '싫은 날', 'file': 'https://docs.google.com/uc?id=1svOJ_72TNX00t1NsuNzXFqvgh9-PVrKv' },
        { 'icon': iconImage, 'title': '애상', 'file': 'https://docs.google.com/uc?id=1PLnz6cCvIRW2-Ykveu6NMaoO_AUQ30I8' },
        { 'icon': iconImage, 'title': '애타는 마음', 'file': 'https://docs.google.com/uc?id=14xTHA5wBfRvqfh_Mw6AsAkRUSg46hzl_' },
        { 'icon': iconImage, 'title': '어제 너는 나를 버렸어', 'file': 'https://docs.google.com/uc?id=1_m8mEetti-hdimfRcf1iz6xefqjGvXhH' },
        { 'icon': iconImage, 'title': '언제나 몇 번이라도 (센과 치히로의 행방불명 OST)', 'file': 'https://docs.google.com/uc?id=1mBCZxUbm27TbVznOkm55p2mBT3CjhyT2' },
        { 'icon': iconImage, 'title': '우주를 줄게', 'file': 'https://docs.google.com/uc?id=1pOMNQeJ6cJN6_HocvL29J6MNt2AbzkuH' },
        { 'icon': iconImage, 'title': '이럴거면 그러지말지', 'file': 'https://docs.google.com/uc?id=1tfAgk9vBMj_RPMMaRMGNIfRM_ZXIkkOC' },
        { 'icon': iconImage, 'title': '이름에게', 'file': 'https://docs.google.com/uc?id=1ge_0VgTIzyrI7L201TRZcg6D-dkrcInK' },
        { 'icon': iconImage, 'title': '이별택시', 'file': 'https://docs.google.com/uc?id=1sYiWszQVR04F8Mf8ct_52JPsIMLNw80f' },
        { 'icon': iconImage, 'title': '이유 갓지 않는 이유', 'file': 'https://docs.google.com/uc?id=1G8P_F4ihielscCFwnp4MIaMi2xviSCFu' },
        { 'icon': iconImage, 'title': '인턴', 'file': 'https://docs.google.com/uc?id=1XfSRzD0G_eSGzK9LYakvc4I3E6g8SR3K' },
        { 'icon': iconImage, 'title': '자격지심', 'file': 'https://docs.google.com/uc?id=1u0wvSDrIIrNNYv5q3THqlErSfZAG9xCZ' },
        { 'icon': iconImage, 'title': '조한이형', 'file': 'https://docs.google.com/uc?id=1i426sa7uk8Z5aLRbrkLK6hSFMjsD-o_m' },
        { 'icon': iconImage, 'title': '징버거 트위치 구독송', 'file': 'https://docs.google.com/uc?id=1ewlE2Y7lbQBiWXj0jz9LnsdzAdrLT5zc' },
        { 'icon': iconImage, 'title': '취기를 빌려', 'file': 'https://docs.google.com/uc?id=1xff5K2PCLgLJgrhJaqEFiC4e6lj3jzUk' },
        { 'icon': iconImage, 'title': '칵테일 사랑', 'file': 'https://docs.google.com/uc?id=1OMUY7RGUf40tjRL3dTLFDr-_qd1KTagl' },
    ]
});