
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '12시 30분', 'file': '' },
        { 'icon': iconImage, 'title': '17171771', 'file': '' },
        { 'icon': iconImage, 'title': '가까이 하고싶은 그대', 'file': '' },
        { 'icon': iconImage, 'title': '가끔', 'file': '' },
        { 'icon': iconImage, 'title': '가질수 없는 너(1.30)', 'file': '' },
        { 'icon': iconImage, 'title': '가질수 없는 너', 'file': '' },
        { 'icon': iconImage, 'title': '고속도로 Romance', 'file': '' },
        { 'icon': iconImage, 'title': '그대라는 사치', 'file': '' },
        { 'icon': iconImage, 'title': '그대만 있다면', 'file': '' },
        { 'icon': iconImage, 'title': '그래도 나 사랑하지 (1.30)', 'file': '' },
        { 'icon': iconImage, 'title': '그래도 나 사랑하지', 'file': '' },
        { 'icon': iconImage, 'title': '금요일에 만나요', 'file': '' },
        { 'icon': iconImage, 'title': '나를 너에게', 'file': '' },
        { 'icon': iconImage, 'title': '나를 슬프게 하는 사람들', 'file': '' },
        { 'icon': iconImage, 'title': '나만 안되는 연애', 'file': '' },
        { 'icon': iconImage, 'title': '낭만고양이', 'file': '' },
        { 'icon': iconImage, 'title': '내 꿈은 파티시엘', 'file': '' },
        { 'icon': iconImage, 'title': '내 손을 잡아', 'file': '' },
        { 'icon': iconImage, 'title': '내꺼야', 'file': '' },
        { 'icon': iconImage, 'title': '너는 내 남자', 'file': '' },
        { 'icon': iconImage, 'title': '너랑 나', 'file': '' },
        { 'icon': iconImage, 'title': '너에게 주고 싶은 세 가지', 'file': '' },
        { 'icon': iconImage, 'title': '너의 의미', 'file': '' },
        { 'icon': iconImage, 'title': '달리기', 'file': '' },
        { 'icon': iconImage, 'title': '답답한 새벽', 'file': '' },
        { 'icon': iconImage, 'title': '두근두근', 'file': '' },
        { 'icon': iconImage, 'title': '말이 안돼', 'file': '' },
        { 'icon': iconImage, 'title': '밤편지(1.30)', 'file': '' },
        { 'icon': iconImage, 'title': '밤편지', 'file': '' },
        { 'icon': iconImage, 'title': '복숭아', 'file': '' },
        { 'icon': iconImage, 'title': '불장난', 'file': '' },
        { 'icon': iconImage, 'title': '삐딱하게', 'file': '' },
        { 'icon': iconImage, 'title': '사랑은 열린 문', 'file': '' },
        { 'icon': iconImage, 'title': '사랑한다는 흔한 말', 'file': '' },
        { 'icon': iconImage, 'title': '사이렌 Remix', 'file': '' },
        { 'icon': iconImage, 'title': '삭제', 'file': '' },
        { 'icon': iconImage, 'title': '삼촌', 'file': '' },
        { 'icon': iconImage, 'title': '상상더하기', 'file': '' },
        { 'icon': iconImage, 'title': '서시', 'file': '' },
        { 'icon': iconImage, 'title': '소주 한 잔', 'file': '' },
        { 'icon': iconImage, 'title': '솜사탕', 'file': '' },
        { 'icon': iconImage, 'title': '수고했어 오늘도', 'file': '' },
        { 'icon': iconImage, 'title': '시간아 천천히', 'file': '' },
        { 'icon': iconImage, 'title': '싫은 날', 'file': '' },
        { 'icon': iconImage, 'title': '썸 탈거야', 'file': '' },
        { 'icon': iconImage, 'title': '애상', 'file': '' },
        { 'icon': iconImage, 'title': '애타는 마음', 'file': '' },
        { 'icon': iconImage, 'title': '야야야', 'file': '' },
        { 'icon': iconImage, 'title': '어제 나는 너를 버렸어', 'file': '' },
        { 'icon': iconImage, 'title': '언제나 몇 번이라도', 'file': '' },
        { 'icon': iconImage, 'title': '우주를 줄게', 'file': '' },
        { 'icon': iconImage, 'title': '이럴거면 그러지말지', 'file': '' },
        { 'icon': iconImage, 'title': '이름에게', 'file': '' },
        { 'icon': iconImage, 'title': '이별택시', 'file': '' },
        { 'icon': iconImage, 'title': '이유 같지 않은 이유', 'file': '' },
        { 'icon': iconImage, 'title': '인턴', 'file': '' },
        { 'icon': iconImage, 'title': '자격지심', 'file': '' },
        { 'icon': iconImage, 'title': '잔소리', 'file': '' },
        { 'icon': iconImage, 'title': '장난기 기능', 'file': '' },
        { 'icon': iconImage, 'title': '정류장', 'file': '' },
        { 'icon': iconImage, 'title': '조한이형', 'file': '' },
        { 'icon': iconImage, 'title': '지름길로 가고파', 'file': '' },
        { 'icon': iconImage, 'title': '징버거 트위치 구독송', 'file': '' },
        { 'icon': iconImage, 'title': '취기를 빌려', 'file': '' },
        { 'icon': iconImage, 'title': '카누를 타고 파라다이스에 갈 때', 'file': '' },
        { 'icon': iconImage, 'title': '칵테일 사랑', 'file': '' },
        { 'icon': iconImage, 'title': '킬리만자로의 표범', 'file': '' },
        { 'icon': iconImage, 'title': '팬서비스', 'file': '' },
        { 'icon': iconImage, 'title': '폰서트', 'file': '' },
        { 'icon': iconImage, 'title': '하하하쏭', 'file': '' },
        { 'icon': iconImage, 'title': '홍련화', 'file': '' },
        { 'icon': iconImage, 'title': 'Ballerio', 'file': '' },
        { 'icon': iconImage, 'title': 'Blinding Light', 'file': '' },
        { 'icon': iconImage, 'title': 'Butter', 'file': '' },
        { 'icon': iconImage, 'title': 'Cant Take My Eyes off You', 'file': '' },
        { 'icon': iconImage, 'title': 'DAN DAN', 'file': '' },
        { 'icon': iconImage, 'title': '데칼코마니', 'file': '' },
        { 'icon': iconImage, 'title': 'FANCY', 'file': '' },
        { 'icon': iconImage, 'title': 'Good-Bye Days', 'file': '' },
        { 'icon': iconImage, 'title': 'I GO', 'file': '' },
        { 'icon': iconImage, 'title': 'Im Yours', 'file': '' },
        { 'icon': iconImage, 'title': 'illa illa', 'file': '' },
        { 'icon': iconImage, 'title': 'Je Taime', 'file': '' },
        { 'icon': iconImage, 'title': 'Madeleine Love', 'file': '' },
        { 'icon': iconImage, 'title': 'Martini Blue', 'file': '' },
        { 'icon': iconImage, 'title': 'Mr. Chu', 'file': '' },
        { 'icon': iconImage, 'title': 'Orange', 'file': '' },
        { 'icon': iconImage, 'title': 'party', 'file': '' },
        { 'icon': iconImage, 'title': 'Reminiscence Overture', 'file': '' },
        { 'icon': iconImage, 'title': 'Rolling In The Deep', 'file': '' },
        { 'icon': iconImage, 'title': 'Shooting Love', 'file': '' },
        { 'icon': iconImage, 'title': 'Speachless', 'file': '' },
        { 'icon': iconImage, 'title': 'Square(2017)', 'file': '' },
        { 'icon': iconImage, 'title': 'Star Bubble', 'file': '' },
        { 'icon': iconImage, 'title': 'STAY', 'file': '' },
        { 'icon': iconImage, 'title': 'strawberry moon', 'file': '' },
        { 'icon': iconImage, 'title': 'Take On Me', 'file': '' },
        { 'icon': iconImage, 'title': 'Villain', 'file': '' },
    ]
});