
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        {'icon': iconImage, 'title': '17171771', 'file': 'https://docs.google.com/uc?id=1nki6fPXkKoHltPKgt1w_QyrN4_3oZ2e_' },
        {'icon': iconImage, 'title': '가까이 하고 싶은 그대', 'file': 'https://docs.google.com/uc?id=1x9KSegASCkVsjZm7UpBU8k--73gMePUo' },
        {'icon': iconImage, 'title': '가질 수 없는 너', 'file': 'https://docs.google.com/uc?id=1eo5anW6E7X3y3vWaa2-MS99LVhQGEldX' },
        {'icon': iconImage, 'title': '고속도로 Romance', 'file': 'https://docs.google.com/uc?id=1imxS8dFlYF8BFosyBsmrp_Ykr3a7LkAf' },
        {'icon': iconImage, 'title': '그대라는 사치', 'file': 'https://docs.google.com/uc?id=1pGBvn_xhqMriQ6HYSV-ipMAyF86U3Ufd' },
        {'icon': iconImage, 'title': '그대만 있다면', 'file': 'https://docs.google.com/uc?id=1gi5w6VVdr0mv_6RFqbcfHvOoAEatKxB4' },
        {'icon': iconImage, 'title': '그래도 나 사랑하지', 'file': 'https://docs.google.com/uc?id=1yp7Ehe6cGvtgYQktNCE99aX_eTCkQ0Jv' },
        {'icon': iconImage, 'title': '금요일에 만나요', 'file': 'https://docs.google.com/uc?id=1aiALd_VY5Eeca4-k00_U-hBXAyKQAFE3' },
        {'icon': iconImage, 'title': '나를 너에게', 'file': 'https://docs.google.com/uc?id=15xJ2AjuWMKVdetF4sL-JYsbAut1IQByJ' },
        {'icon': iconImage, 'title': '나를 슬프게 하는 사람들', 'file': 'https://docs.google.com/uc?id=1LcKhcKiVqlw3GLCaHUU5Qc2iGSGTmDFd' },
        {'icon': iconImage, 'title': '나만 안되는 연애', 'file': 'https://docs.google.com/uc?id=107hf6d85G2HOoTyZeJzSeRNj0fOtjWBX' },
        {'icon': iconImage, 'title': '낭만고양이', 'file': 'https://docs.google.com/uc?id=1yWJkDoUBLRRT1UlHjW-n2gz69_6xgFIZ' },
        {'icon': iconImage, 'title': '내 손을 잡아', 'file': 'https://docs.google.com/uc?id=1__BQ1b2Nvhce4VPHiEAcggAtWpw_Nb1V' },
        {'icon': iconImage, 'title': '내꺼야', 'file': 'https://docs.google.com/uc?id=1HTY_GFBd2UQxkPDnv9e6CxS85BUemNzJ' },
        {'icon': iconImage, 'title': '너는 내 남자', 'file': 'https://docs.google.com/uc?id=18arDLj9Rq9UWwNE5EVFruZMcB957d5aD' },
        {'icon': iconImage, 'title': '너랑 나', 'file': 'https://docs.google.com/uc?id=18k35IEdfNu09hYcRO7TPxinVMaT3vZ9k' },
        {'icon': iconImage, 'title': '너의 의미', 'file': 'https://docs.google.com/uc?id=1fyvFGFPtz70SC9DDtBaWGPdgLiL9yWqC' },
        {'icon': iconImage, 'title': '달리기', 'file': 'https://docs.google.com/uc?id=1XK8SZIhtF5aEPq5XXSbxnUZA2rOVqQD6' },
        {'icon': iconImage, 'title': '답답한 새벽', 'file': 'https://docs.google.com/uc?id=14Y5ScXJJwSrcLFuK6W-va9A4T_-y4B09' },
        {'icon': iconImage, 'title': '두근두근', 'file': 'https://docs.google.com/uc?id=1PDxlgoerjf2mRny5zHHB_-GPtDlsOU9r' },
        {'icon': iconImage, 'title': '말도 안돼 (개인의 취향 OST)', 'file': 'https://docs.google.com/uc?id=1bcdXQPe3lUy4MfaAR6N2L37xWkvNAuXp' },
        {'icon': iconImage, 'title': '무릎', 'file': 'https://docs.google.com/uc?id=1BeBhw7knZ3aTSXX6Rpqx9rEmblAw5Us3' },
        {'icon': iconImage, 'title': '밤편지', 'file': 'https://docs.google.com/uc?id=1mVFPUur2KO0_fLLRENlp-PlcGsjCloTA' },
        {'icon': iconImage, 'title': '복숭아', 'file': 'https://docs.google.com/uc?id=1bwQG80YZfrUf-SdoPSk4FP9SD7FzXyGy' },
        {'icon': iconImage, 'title': '불장난', 'file': 'https://docs.google.com/uc?id=1oPofS5zhhj2XPe7CiYLA3j6qlnOEtuIo' },
        {'icon': iconImage, 'title': '삐딱하게', 'file': 'https://docs.google.com/uc?id=1UI7klbBwNbAAiVKTbwQtr_7vJF3oilUh' },
        {'icon': iconImage, 'title': '사랑한다는 흔한 말', 'file': 'https://docs.google.com/uc?id=10fO3cooTFV-vp_1G1NAU3UMLyUGMh9sp' },
        {'icon': iconImage, 'title': '사이렌 Remix', 'file': 'https://docs.google.com/uc?id=1ec30TTApKO1HzDKKOhpTjZXSuVVRWik_' },
        {'icon': iconImage, 'title': '삭제', 'file': 'https://docs.google.com/uc?id=1mppm48PWkTGgMzRAo643GUON4AcBBNlo' },
        {'icon': iconImage, 'title': '삼촌', 'file': 'https://docs.google.com/uc?id=1YWMJcpvj0e-ceIZawpvw_3mdIRburi0P' },
        {'icon': iconImage, 'title': '상상더하기', 'file': 'https://docs.google.com/uc?id=1oJHZP_eT-_d7JOr4JnGL0ko_sZcbokEg' },
        {'icon': iconImage, 'title': '서시', 'file': 'https://docs.google.com/uc?id=1v00qztyc3g-Q0iv24efnPq-Z_8QUstlZ' },
        {'icon': iconImage, 'title': '수고했어 오늘도', 'file': 'https://docs.google.com/uc?id=1nOEZXkJyql85c7jCEn8HEswC3Joc3cfX' },
        {'icon': iconImage, 'title': '시간아 천천히', 'file': 'https://docs.google.com/uc?id=1LUKB1DBbYrNRsRiEy13IuHz5MPB6I95J' },
        {'icon': iconImage, 'title': '싫은 날', 'file': 'https://docs.google.com/uc?id=1tbHmA19MxI7LCug4whpj_hlX2kgYfk8i' },
        {'icon': iconImage, 'title': '애상', 'file': 'https://docs.google.com/uc?id=1q_qoqyu6KXTY4WB_Fs9GSaH8I-2zsdyo' },
        {'icon': iconImage, 'title': '애타는 마음', 'file': 'https://docs.google.com/uc?id=19Wh_MKYDR07c8XWClmH_zBOFns4MqB-u' },
        {'icon': iconImage, 'title': '어제 너는 나를 버렸어', 'file': 'https://docs.google.com/uc?id=1idMtNm94xU5o7gN1QrD9ASkggo1B9sh0' },
        {'icon': iconImage, 'title': '언제나 몇 번이라도 (센과 치히로의 행방불명 OST)', 'file': 'https://docs.google.com/uc?id=19fozizB-i2gC95LGZ_esoxZ7oT0rzmih' },
        {'icon': iconImage, 'title': '우주를 줄게', 'file': 'https://docs.google.com/uc?id=1-eM76TwWmpbFeQLIUDRKhrKYa8TC_FbO' },
        {'icon': iconImage, 'title': '이럴거면 그러지말지', 'file': 'https://docs.google.com/uc?id=1iRBL-kftLsdwAEUpbf2i7-HrkOX1dFDx' },
        {'icon': iconImage, 'title': '이름에게', 'file': 'https://docs.google.com/uc?id=1PF9lC_aB9rIOhrrbFsj2uoNo5oyrshv8' },
        {'icon': iconImage, 'title': '이별택시', 'file': 'https://docs.google.com/uc?id=1RKmjn9Ax61TxgnqarUfFYmHilNsGGorM' },
        {'icon': iconImage, 'title': '이유 갓지 않는 이유', 'file': 'https://docs.google.com/uc?id=1jrSGQVh4rrOhoeeUz0wN78wybEN84c6n' },
        {'icon': iconImage, 'title': '인턴', 'file': 'https://docs.google.com/uc?id=1a6IIcZSCoARHbBaRgwwkZxo_Vig7KQn3' },
        {'icon': iconImage, 'title': '자격지심', 'file': 'https://docs.google.com/uc?id=1uXccwLEhWBUx869KZEGKcJQbfUuONZJK' },
        {'icon': iconImage, 'title': '조한이형', 'file': 'https://docs.google.com/uc?id=1H5xSkFiMqmc0ONaqK0kygNqpC1H2GfDZ' },
        {'icon': iconImage, 'title': '징버거 트위치 구독송', 'file': 'https://docs.google.com/uc?id=1H5phFUkK4UiAlROWvVY0aiJFfGd5KAJZ' },
        {'icon': iconImage, 'title': '취기를 빌려', 'file': 'https://docs.google.com/uc?id=1h9IpCsfxf2V8JIia-87JBPnu0rkyJGt4' },
        {'icon': iconImage, 'title': '칵테일 사랑', 'file': 'https://docs.google.com/uc?id=1FTyRKCyKuJv_SrdyLtL9W_ER4FhMkV_Y' },
    ]
});