
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '첫이별그날밤', 'file': 'https://docs.google.com/uc?id=1OPNm2W-f9Yo1eCQQ_nJ6jRjwcxh4q_fk' },
        { 'icon': iconImage, 'title': '사랑인듯 아닌듯', 'file': 'https://docs.google.com/uc?id=1PXtWlaJcAhT4sJ8ogAtJ847qyjf7lmSD' },
        { 'icon': iconImage, 'title': '네가 좋아', 'file': 'https://docs.google.com/uc?id=1Dt3eHwMwpq_HCr3Rw0C210a8N6dsnEb9' },
        { 'icon': iconImage, 'title': '좋아좋아', 'file': 'https://docs.google.com/uc?id=15vW8x4B-bNmOh4C2BEiLVFaE66v9rLL6' },
        { 'icon': iconImage, 'title': '빌런', 'file': 'https://docs.google.com/uc?id=1rPgYLH6hogeFj4ludQpLgxDIjOWznYcD' },
        { 'icon': iconImage, 'title': '고속도로 로망스', 'file': 'https://docs.google.com/uc?id=1YQUl5gVoSWGiIw9APvvoHt8SLK1Ng6tu' },
        { 'icon': iconImage, 'title': '랄랄라', 'file': 'https://docs.google.com/uc?id=17SBTroXxEKkrG3DaZmMEhRoCRqlZ57sO' },
        { 'icon': iconImage, 'title': '어떻게 생각해', 'file': 'https://docs.google.com/uc?id=1hOW6dEmk0a_8mCtr-Vfo2yMLVQckBDeS' },
        { 'icon': iconImage, 'title': 'First Kiss', 'file': 'https://docs.google.com/uc?id=1Ua2SwLr78IKQwaezeRIzb7UOWULa3-kQ' },
        { 'icon': iconImage, 'title': 'dream dream dream', 'file': 'https://docs.google.com/uc?id=14k-_E1pMiYrHIlwRj-UtmiI5sHhgnyUR' },
        { 'icon': iconImage, 'title': 'Someday', 'file': 'https://docs.google.com/uc?id=129NfOegdhg2nLsYLBJ0MrCcPwou63bVn' },
        { 'icon': iconImage, 'title': 'Melody', 'file': 'https://docs.google.com/uc?id=1-IlbiQEU1zZatsFUdtG0Bdz4d4dqPh4h' },
        { 'icon': iconImage, 'title': '늦은 후회', 'file': 'https://docs.google.com/uc?id=1uZYbIp1vpXCMgbF33fEQb79gYewHmSR9' },
        { 'icon': iconImage, 'title': 'love day', 'file': 'https://docs.google.com/uc?id=1wDokFYkTiii7ibo6wP0BTTh4OL8BPl-t' },
        { 'icon': iconImage, 'title': 'Evolution song', 'file': 'https://docs.google.com/uc?id=1zieK2VfgPfwXURvcogOEIxCEHu0bZvcD' },
        { 'icon': iconImage, 'title': 'Power up', 'file': 'https://docs.google.com/uc?id=1Hd55vKYI06xuJ0eg5ACcd9KWdO24Dn8m' },
        { 'icon': iconImage, 'title': 'New future', 'file': 'https://docs.google.com/uc?id=1N1IbUuIUGgusXJqhk7nuc705zJDpfWeE' },
        { 'icon': iconImage, 'title': '러브크로니클', 'file': 'https://docs.google.com/uc?id=1An2YAn58SRzjdApYQBQa2PhvPuGWqgeU' },
        { 'icon': iconImage, 'title': '또다른나', 'file': 'https://docs.google.com/uc?id=12caLW1hT0-dKxzMjAUqc0ptxTm21aEuh' },
        { 'icon': iconImage, 'title': 'Grow up', 'file': 'https://docs.google.com/uc?id=1a3ZfUYPjWDkVzxtjR8HuMRfc1n93Y7YV' },
        { 'icon': iconImage, 'title': '안녕 디지몬', 'file': 'https://docs.google.com/uc?id=1rxmF9hbIG6oePnk4zzV-bgUGWiz7jo23' },
        { 'icon': iconImage, 'title': 'To my wish', 'file': 'https://docs.google.com/uc?id=1GFpHh27jXU2twW5eVqpcVR3dTnmsWB5f' },
        { 'icon': iconImage, 'title': '너를 위한 Try', 'file': 'https://docs.google.com/uc?id=1XQrKE5YEzeRgyuZ4hMJ82vvHzUhzYIh2' },
        { 'icon': iconImage, 'title': '출사표', 'file': 'https://docs.google.com/uc?id=1NRq3KobMC2pxo4ZQORj3DIuFjWenn3nD' },
        { 'icon': iconImage, 'title': '지름길로 가고파', 'file': 'https://docs.google.com/uc?id=1l0uosUi02L-FMPnar5L8DLJyxufoM2Sq' },
        { 'icon': iconImage, 'title': '그래그래', 'file': 'https://docs.google.com/uc?id=1RTyEVVyhmqfDqowkRq3jvHWGeZoHIcVS' },
        { 'icon': iconImage, 'title': '사랑의 구조신호', 'file': 'https://docs.google.com/uc?id=1REHjfsbxSq5x8IvLvQqVMEcAGHo30czk' },
        { 'icon': iconImage, 'title': 'Catch you catch me', 'file': 'https://docs.google.com/uc?id=1awmaCFRkXTqNzzh0Pga2LK5jk1VUBPDZ' },
        { 'icon': iconImage, 'title': '10cm - 너에게 닿기를', 'file': 'https://docs.google.com/uc?id=1dLg5IqcHOP7ruV7Ch9mOufhUzr-C-eBb' },
        { 'icon': iconImage, 'title': '프로듀스 - 너에게 닿기를', 'file': 'https://docs.google.com/uc?id=1wpUDQaQw5YyzR9KIb7oY3W-lPR3O3RJD' },
        { 'icon': iconImage, 'title': '우주소녀 - 너에게 닿기를', 'file': 'https://docs.google.com/uc?id=1sRV38LaokX6TG7NN7s-q9Lyv_pEc6mcC' },
        { 'icon': iconImage, 'title': '우주를 줄게', 'file': 'https://docs.google.com/uc?id=1_uLl-q3pnk7-FijAJ82ydWSKid_SLnE8' },
        { 'icon': iconImage, 'title': '일레븐', 'file': 'https://docs.google.com/uc?id=1UM9ByvLcDDvEebeW6_n00WsfJPJGcbsX' },
        { 'icon': iconImage, 'title': '라비앙로즈', 'file': 'https://docs.google.com/uc?id=1NZFY5zCT8wcO6mTpk9nlefs-t4kyyyd8' },
        { 'icon': iconImage, 'title': '여우야', 'file': 'https://docs.google.com/uc?id=1nALncCnCzU8z3dvgzXum6RHzg93mz32g' },
        { 'icon': iconImage, 'title': '여우비', 'file': 'https://docs.google.com/uc?id=14471f4SH6YwIT6c8-3tiKrcal3XqRTuw' },
        { 'icon': iconImage, 'title': '잠시 길을 잃다', 'file': 'https://docs.google.com/uc?id=1f13FghNTw0SF17c4y7DjEg-HIYUNKCU3' },
        { 'icon': iconImage, 'title': '1월부터 6월까지', 'file': 'https://docs.google.com/uc?id=1UWwx1Yk2IL-o_4AFk2zwNwkGoSHmr2hs' },
        { 'icon': iconImage, 'title': '서면역에서', 'file': 'https://docs.google.com/uc?id=1UlgW9mWnvGeznjJXdx-sMaeZSKY91S6c' },
        { 'icon': iconImage, 'title': '사랑스러워', 'file': 'https://docs.google.com/uc?id=10ImnwS5wxv38duOaopfurstKMSHHxH-D' },
        { 'icon': iconImage, 'title': '내 남자친구에게', 'file': 'https://docs.google.com/uc?id=1oSPg1AWkw-zxdjaWMsTJvfmDkxw57ETm' },
        { 'icon': iconImage, 'title': 'love love love', 'file': 'https://docs.google.com/uc?id=1UwvcGIuTEh-KlG4CW8qj97U6bZo6-VHB' },
        { 'icon': iconImage, 'title': 'Kiss me', 'file': 'https://docs.google.com/uc?id=16AxKDMY2x_E2z_6VeonTDT_cM4iZYbLC' },
        { 'icon': iconImage, 'title': '니가 참 좋아', 'file': 'https://docs.google.com/uc?id=1IOzDU1y8Kd_5zKinVwA103Tgzg1GpIFM' },
        { 'icon': iconImage, 'title': 'Happy day', 'file': 'https://docs.google.com/uc?id=15xIyDGO1HC3OLO1Xy2VykVomi4ZTxdGS' },
        { 'icon': iconImage, 'title': '안녕', 'file': 'https://docs.google.com/uc?id=1mNFBEPFy12jnB8ZiFd6saSmdgDFPeJze' },
        { 'icon': iconImage, 'title': '사랑의 트위스트', 'file': 'https://docs.google.com/uc?id=1bw6LR-2s8bSBt4VfYpwIBuv5ldYcT9Wf' },
        { 'icon': iconImage, 'title': '해변의 여인', 'file': 'https://docs.google.com/uc?id=1qq4zih6tTTB1tjNvN8sw_ISlJK0Kf1H6' },
        { 'icon': iconImage, 'title': '일과 이분의 일', 'file': 'https://docs.google.com/uc?id=1Krx8y5J8fwLSmA80fNSkubdOWBnk_a_8' },
        { 'icon': iconImage, 'title': '행복', 'file': 'https://docs.google.com/uc?id=1EyWpauEtBUipstF39EevkT_j5z7qFIwp' },
        { 'icon': iconImage, 'title': 'White', 'file': 'https://docs.google.com/uc?id=1HifjU7G9p9Z-IteS25o3zOUKIXW61Rf7' },
        { 'icon': iconImage, 'title': '풍선', 'file': 'https://docs.google.com/uc?id=1nK932Rf66O_-phpfwj5boydZh7gy3qAA' },
        { 'icon': iconImage, 'title': '붉은 노을', 'file': 'https://docs.google.com/uc?id=1kbu_1Q4n-8cd2027n9FhPD1QTZUwMAqs' },
        { 'icon': iconImage, 'title': '버스안에서', 'file': 'https://docs.google.com/uc?id=1m83wnEMp_UhJajwr1MbTmb-UTJoPcEmH' },
        { 'icon': iconImage, 'title': '섹시한 남자', 'file': 'https://docs.google.com/uc?id=1sUp21Tj8Jk1_px1F2kZh-S9RUj8zaR1s' },
        { 'icon': iconImage, 'title': '밤편지', 'file': 'https://docs.google.com/uc?id=1aypOJkIfoOE4Z9lt89Fy4soCzBc3FaxF' },
        { 'icon': iconImage, 'title': '폰서트', 'file': 'https://docs.google.com/uc?id=1SmOp7MboN81-ylOMbvfadw_WSjX7-SK4' },
        { 'icon': iconImage, 'title': '애인을 내려주세요', 'file': 'https://docs.google.com/uc?id=13yyaJ5372cm2JSYkVYFPKfgJ5AQozY7X' },
        { 'icon': iconImage, 'title': '예뻤어', 'file': 'https://docs.google.com/uc?id=1pqjiLWvyZSmOdWK8KtBqdT3uwICApAg3' },
        { 'icon': iconImage, 'title': '힘내', 'file': 'https://docs.google.com/uc?id=1a5iXOmsQ4sGdk1_elu9q8UE-npXe94ST' },
        { 'icon': iconImage, 'title': 'Full moon', 'file': 'https://docs.google.com/uc?id=1J1dlCeNYimGuJkDs7o1rtH1AysUSJTkr' },
        { 'icon': iconImage, 'title': 'Just 4 U', 'file': 'https://docs.google.com/uc?id=1RESyY183SD0Gaw2AqSyeV2PoCzllqnPW' },


    ]
});