
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '1. 첫이별그날밤.x264.aac', 'file': 'https://docs.google.com/uc?id=1OPNm2W-f9Yo1eCQQ_nJ6jRjwcxh4q_fk' },
        { 'icon': iconImage, 'title': '2. 사랑인듯 아닌듯.x264.aac', 'file': 'https://docs.google.com/uc?id=1PXtWlaJcAhT4sJ8ogAtJ847qyjf7lmSD' },
        { 'icon': iconImage, 'title': '네가 좋아.x264.aac', 'file': 'https://docs.google.com/uc?id=1Dt3eHwMwpq_HCr3Rw0C210a8N6dsnEb9' },
        { 'icon': iconImage, 'title': '4. 좋아좋아.x264.aac', 'file': 'https://docs.google.com/uc?id=15vW8x4B-bNmOh4C2BEiLVFaE66v9rLL6' },
        { 'icon': iconImage, 'title': '5. 빌런.x264.aac', 'file': 'https://docs.google.com/uc?id=1rPgYLH6hogeFj4ludQpLgxDIjOWznYcD' },
        { 'icon': iconImage, 'title': '6. 고속도로 로망스.x264.aac', 'file': 'https://docs.google.com/uc?id=1YQUl5gVoSWGiIw9APvvoHt8SLK1Ng6tu' },
        { 'icon': iconImage, 'title': '7. 랄랄라.x264.aac', 'file': 'https://docs.google.com/uc?id=17SBTroXxEKkrG3DaZmMEhRoCRqlZ57sO' },
        { 'icon': iconImage, 'title': '8. 어떻게 생각해', 'file': 'https://docs.google.com/uc?id=1hOW6dEmk0a_8mCtr-Vfo2yMLVQckBDeS' },
        { 'icon': iconImage, 'title': '9. First Kiss.x264.aac', 'file': 'https://docs.google.com/uc?id=1Ua2SwLr78IKQwaezeRIzb7UOWULa3-kQ' },
        { 'icon': iconImage, 'title': '10. dream dream dream.x264.aac', 'file': 'https://docs.google.com/uc?id=14k-_E1pMiYrHIlwRj-UtmiI5sHhgnyUR' },
        { 'icon': iconImage, 'title': '11. Someday', 'file': 'https://docs.google.com/uc?id=129NfOegdhg2nLsYLBJ0MrCcPwou63bVn' },
        { 'icon': iconImage, 'title': '12. Melody.x264.aac', 'file': 'https://docs.google.com/uc?id=1-IlbiQEU1zZatsFUdtG0Bdz4d4dqPh4h' },
        { 'icon': iconImage, 'title': '13. 늦은 후회.x264.aac', 'file': 'https://docs.google.com/uc?id=1uZYbIp1vpXCMgbF33fEQb79gYewHmSR9' },
        { 'icon': iconImage, 'title': '14. love day.x264.aac', 'file': 'https://docs.google.com/uc?id=1wDokFYkTiii7ibo6wP0BTTh4OL8BPl-t' },
        { 'icon': iconImage, 'title': '15. Evolution song.x264.aac', 'file': 'https://docs.google.com/uc?id=1zieK2VfgPfwXURvcogOEIxCEHu0bZvcD' },
        { 'icon': iconImage, 'title': '16. Power up.x264.aac', 'file': 'https://docs.google.com/uc?id=1Hd55vKYI06xuJ0eg5ACcd9KWdO24Dn8m' },
        { 'icon': iconImage, 'title': '17. New future.x264.aac', 'file': 'https://docs.google.com/uc?id=1N1IbUuIUGgusXJqhk7nuc705zJDpfWeE' },
        { 'icon': iconImage, 'title': '18. 러브크로니클.x264.aac', 'file': 'https://docs.google.com/uc?id=1An2YAn58SRzjdApYQBQa2PhvPuGWqgeU' },
        { 'icon': iconImage, 'title': '19. 또다른나.x264.aac', 'file': 'https://docs.google.com/uc?id=12caLW1hT0-dKxzMjAUqc0ptxTm21aEuh' },
        { 'icon': iconImage, 'title': '20. Grow up.x264.aac', 'file': 'https://docs.google.com/uc?id=1a3ZfUYPjWDkVzxtjR8HuMRfc1n93Y7YV' },
        { 'icon': iconImage, 'title': '21. 안녕 디지몬.x264.aac', 'file': 'https://docs.google.com/uc?id=1rxmF9hbIG6oePnk4zzV-bgUGWiz7jo23' },
        { 'icon': iconImage, 'title': '22. To my wish.x264.aac', 'file': 'https://docs.google.com/uc?id=1GFpHh27jXU2twW5eVqpcVR3dTnmsWB5f' },
        { 'icon': iconImage, 'title': '23. 너를 위한 Try.x264.aac', 'file': 'https://docs.google.com/uc?id=1XQrKE5YEzeRgyuZ4hMJ82vvHzUhzYIh2' },
        { 'icon': iconImage, 'title': '24. 출사표.x264.aac', 'file': 'https://docs.google.com/uc?id=1NRq3KobMC2pxo4ZQORj3DIuFjWenn3nD' },
        { 'icon': iconImage, 'title': '25. 지름길로 가고파.x264.aac', 'file': 'https://docs.google.com/uc?id=1l0uosUi02L-FMPnar5L8DLJyxufoM2Sq' },
        { 'icon': iconImage, 'title': '26. 그래그래.x264.aac', 'file': 'https://docs.google.com/uc?id=1RTyEVVyhmqfDqowkRq3jvHWGeZoHIcVS' },
        { 'icon': iconImage, 'title': '27. 사랑의 구조신호.x264.aac', 'file': 'https://docs.google.com/uc?id=1REHjfsbxSq5x8IvLvQqVMEcAGHo30czk' },
        { 'icon': iconImage, 'title': '28. Catch you catch me.x264.aac', 'file': 'https://docs.google.com/uc?id=1awmaCFRkXTqNzzh0Pga2LK5jk1VUBPDZ' },
        { 'icon': iconImage, 'title': '29. 10cm - 너에게 닿기를.x264.aac', 'file': 'https://docs.google.com/uc?id=1dLg5IqcHOP7ruV7Ch9mOufhUzr-C-eBb' },
        { 'icon': iconImage, 'title': '0. 프로듀스 - 너에게 닿기를.x264.aac', 'file': 'https://docs.google.com/uc?id=1wpUDQaQw5YyzR9KIb7oY3W-lPR3O3RJD' },
        { 'icon': iconImage, 'title': '1. 우주소녀 - 너에게 닿기를.x264.aac', 'file': 'https://docs.google.com/uc?id=1sRV38LaokX6TG7NN7s-q9Lyv_pEc6mcC' },
        { 'icon': iconImage, 'title': '2. 우주를 줄게.x264.aac', 'file': 'https://docs.google.com/uc?id=1_uLl-q3pnk7-FijAJ82ydWSKid_SLnE8' },
        { 'icon': iconImage, 'title': '일레븐.x264.aac', 'file': 'https://docs.google.com/uc?id=1UM9ByvLcDDvEebeW6_n00WsfJPJGcbsX' },
        { 'icon': iconImage, 'title': '4. 라비앙로즈.x264.aac', 'file': 'https://docs.google.com/uc?id=1NZFY5zCT8wcO6mTpk9nlefs-t4kyyyd8' },
        { 'icon': iconImage, 'title': '5. 여우야.x264.aac', 'file': 'https://docs.google.com/uc?id=1nALncCnCzU8z3dvgzXum6RHzg93mz32g' },
        { 'icon': iconImage, 'title': '6. 여우비.x264.aac', 'file': 'https://docs.google.com/uc?id=14471f4SH6YwIT6c8-3tiKrcal3XqRTuw' },
        { 'icon': iconImage, 'title': '7. 잠시 길을 잃다.x264.aac', 'file': 'https://docs.google.com/uc?id=1f13FghNTw0SF17c4y7DjEg-HIYUNKCU3' },
        { 'icon': iconImage, 'title': '8. 1월부터 6월까지.x264.aac', 'file': 'https://docs.google.com/uc?id=1UWwx1Yk2IL-o_4AFk2zwNwkGoSHmr2hs' },
        { 'icon': iconImage, 'title': '9. 서면역에서.x264.aac', 'file': 'https://docs.google.com/uc?id=1UlgW9mWnvGeznjJXdx-sMaeZSKY91S6c' },
        { 'icon': iconImage, 'title': '40. 사랑스러워.x264.aac', 'file': 'https://docs.google.com/uc?id=10ImnwS5wxv38duOaopfurstKMSHHxH-D' },
        { 'icon': iconImage, 'title': '41. 내 남자친구에게.x264.aac', 'file': 'https://docs.google.com/uc?id=1oSPg1AWkw-zxdjaWMsTJvfmDkxw57ETm' },
        { 'icon': iconImage, 'title': '42. love love love.x264.aac', 'file': 'https://docs.google.com/uc?id=1UwvcGIuTEh-KlG4CW8qj97U6bZo6-VHB' },
        { 'icon': iconImage, 'title': '43. Kiss me.x264.aac', 'file': 'https://docs.google.com/uc?id=16AxKDMY2x_E2z_6VeonTDT_cM4iZYbLC' },
        { 'icon': iconImage, 'title': '44. 니가 참 좋아.x264.aac', 'file': 'https://docs.google.com/uc?id=1IOzDU1y8Kd_5zKinVwA103Tgzg1GpIFM' },
        { 'icon': iconImage, 'title': '45. Happy day.x264.aac', 'file': 'https://docs.google.com/uc?id=15xIyDGO1HC3OLO1Xy2VykVomi4ZTxdGS' },
        { 'icon': iconImage, 'title': '46. 안녕.x264.aac', 'file': 'https://docs.google.com/uc?id=1mNFBEPFy12jnB8ZiFd6saSmdgDFPeJze' },
        { 'icon': iconImage, 'title': '47. 사랑의 트위스트.x264.aac', 'file': 'https://docs.google.com/uc?id=1bw6LR-2s8bSBt4VfYpwIBuv5ldYcT9Wf' },
        { 'icon': iconImage, 'title': '48. 해변의 여인.x264.aac', 'file': 'https://docs.google.com/uc?id=1qq4zih6tTTB1tjNvN8sw_ISlJK0Kf1H6' },
        { 'icon': iconImage, 'title': '49. 일과 이분의 일.x264.aac', 'file': 'https://docs.google.com/uc?id=1Krx8y5J8fwLSmA80fNSkubdOWBnk_a_8' },
        { 'icon': iconImage, 'title': '50. 행복.x264.aac', 'file': 'https://docs.google.com/uc?id=1EyWpauEtBUipstF39EevkT_j5z7qFIwp' },
        { 'icon': iconImage, 'title': '51. White.x264.aac', 'file': 'https://docs.google.com/uc?id=1HifjU7G9p9Z-IteS25o3zOUKIXW61Rf7' },
        { 'icon': iconImage, 'title': '52. 풍선.x264.aac', 'file': 'https://docs.google.com/uc?id=1nK932Rf66O_-phpfwj5boydZh7gy3qAA' },
        { 'icon': iconImage, 'title': '53. 붉은 노을.x264.aac', 'file': 'https://docs.google.com/uc?id=1kbu_1Q4n-8cd2027n9FhPD1QTZUwMAqs' },
        { 'icon': iconImage, 'title': '54. 버스안에서.x264.aac', 'file': 'https://docs.google.com/uc?id=1m83wnEMp_UhJajwr1MbTmb-UTJoPcEmH' },
        { 'icon': iconImage, 'title': '55. 섹시한 남자.x264.aac', 'file': 'https://docs.google.com/uc?id=1sUp21Tj8Jk1_px1F2kZh-S9RUj8zaR1s' },
        { 'icon': iconImage, 'title': '56. 밤편지.x264.aac', 'file': 'https://docs.google.com/uc?id=1aypOJkIfoOE4Z9lt89Fy4soCzBc3FaxF' },
        { 'icon': iconImage, 'title': '57. 폰서트.x264.aac', 'file': 'https://docs.google.com/uc?id=1SmOp7MboN81-ylOMbvfadw_WSjX7-SK4' },
        { 'icon': iconImage, 'title': '애인을 내려주세요', 'file': 'https://docs.google.com/uc?id=13yyaJ5372cm2JSYkVYFPKfgJ5AQozY7X' },
        { 'icon': iconImage, 'title': '예뻤어', 'file': 'https://docs.google.com/uc?id=1pqjiLWvyZSmOdWK8KtBqdT3uwICApAg3' },
        { 'icon': iconImage, 'title': '힘내', 'file': 'https://docs.google.com/uc?id=1a5iXOmsQ4sGdk1_elu9q8UE-npXe94ST' },
        { 'icon': iconImage, 'title': 'Full moon', 'file': 'https://docs.google.com/uc?id=1J1dlCeNYimGuJkDs7o1rtH1AysUSJTkr' },
        { 'icon': iconImage, 'title': 'Just 4 U', 'file': 'https://docs.google.com/uc?id=1RESyY183SD0Gaw2AqSyeV2PoCzllqnPW' },


    ]
});