
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '10cm - pet', 'file': 'https://docs.google.com/uc?id=1RyAVdE9z-G1O2G9EjNz1KNu4vZjdKGvY' },
        { 'icon': iconImage, 'title': '김광진 - 편지', 'file': 'https://docs.google.com/uc?id=1Eq8o-HClzKsVsLVo7xAF7mJdrRXX8Fu8' },
        { 'icon': iconImage, 'title': '나와 호랑이님 OST - 호랑수월가', 'file': 'https://docs.google.com/uc?id=1b2RkjBEdYdX9onxnImjWC7espIqbQLi9' },
        { 'icon': iconImage, 'title': '너의이름은 OST - 아무것도 아니야', 'file': 'https://docs.google.com/uc?id=1TFbQZieHnCEEVu_zeJHrQ4ECsjtAcOzk' },
        { 'icon': iconImage, 'title': '달의하루 - 염라', 'file': 'https://docs.google.com/uc?id=1mV8PLb72E4C1yAy4FxMqHOOWouWIOqkg' },
        { 'icon': iconImage, 'title': '라디오헤드 - Cree', 'file': 'https://docs.google.com/uc?id=1paSlSAbwGifQXj-HaOdTFEmDFCOjn7gV' },
        { 'icon': iconImage, 'title': '라푼젤 OST - When Will My Life Begin', 'file': 'https://docs.google.com/uc?id=1gqINfqj9B_Un3n2PFVpUwfubV3IEw6tC' },
        { 'icon': iconImage, 'title': '마루코는 아홉살 OST - 춤춰요 폼포코링', 'file': 'https://docs.google.com/uc?id=11oa3XGb1ag5fyC7VliPoPVvA5RCCfXro' },
        { 'icon': iconImage, 'title': '머라이어 캐리 , 휘트니 휴스턴 - When you Believe', 'file': 'https://docs.google.com/uc?id=1usWFi7RD0_YkDZCZK3yWeWnk_Avnw_p0' },
        { 'icon': iconImage, 'title': '뮤지컬 레베카 - 레베카', 'file': 'https://docs.google.com/uc?id=1Z5hleRdyXUpj4LZD6I0n1ndmjCX7UD1_' },
        { 'icon': iconImage, 'title': '뮤지컬 위키드 OST - Defying Gravity', 'file': 'https://docs.google.com/uc?id=1iXCmx647912je2olA4Tv5iKOEsmgA5Hc' },
        { 'icon': iconImage, 'title': '뮤지컬 캣츠 OST 바브라 스트라이샌드 - Memory', 'file': 'https://docs.google.com/uc?id=1PITWLANhLPtqOiXog1hfbPtifNPdgubV' },
        { 'icon': iconImage, 'title': '벤 - 꿈처럼', 'file': 'https://docs.google.com/uc?id=1xiM94_IeQRpuiiw931eGvFDgQ4UMyYSM' },
        { 'icon': iconImage, 'title': '비욘세 - Listen', 'file': 'https://docs.google.com/uc?id=1yCiq5WJMFiN5ZEFQ3LLUuNiNRG1d6Yut' },
        { 'icon': iconImage, 'title': '비챤생일축하', 'file': 'https://docs.google.com/uc?id=1pAhmzzpdNYeoKl2Bg0OkJitwjjH9fIEu' },
        { 'icon': iconImage, 'title': '샘 스미스 - Lay me down', 'file': 'https://docs.google.com/uc?id=1SfAXXqn204KydQNKjTBL0GNJWrGT9ahN' },
        { 'icon': iconImage, 'title': '선우정아 - 도망가자', 'file': 'https://docs.google.com/uc?id=1Gl2uC0XhTcVvRSDI4XljuuJECUfVMNPs' },
        { 'icon': iconImage, 'title': '성시경 - 너의 모든 순간', 'file': 'https://docs.google.com/uc?id=1ir8hx5G_QLcXCZNl68GiOgGm_xNzq1JZ' },
        { 'icon': iconImage, 'title': '송소희 -달무리', 'file': 'https://docs.google.com/uc?id=1Y70bM20MZ8wqzKPFMqOwN_UpaIGG1PaD' },
        { 'icon': iconImage, 'title': '심규선 - 아라리', 'file': 'https://docs.google.com/uc?id=1p5rUyB6Mb5RNAiDTWr9iXSweFhZ7MxJ_' },
        { 'icon': iconImage, 'title': '심규선- 화조도', 'file': 'https://docs.google.com/uc?id=1gssWEpCuvMCr-2OtUylL_jaSpVVgtHYO' },
        { 'icon': iconImage, 'title': '아델 - When we were young', 'file': 'https://docs.google.com/uc?id=1Y7VbDaCkKjz8ze2AP1QGM6WNwYKhdpQP' },
        { 'icon': iconImage, 'title': '아리아나 그란데  - Dangerous Woman', 'file': 'https://docs.google.com/uc?id=1marS77hIfHMoZxTZIKKAXrB9sDt0vJkr' },
        { 'icon': iconImage, 'title': '아리아나 그란데 - almost is never enough', 'file': 'https://docs.google.com/uc?id=1OUMqVPvtcBJr9Th4Ua7CUrm7jnHA6Rkm' },
        { 'icon': iconImage, 'title': '아리아나 그란데 - One last time', 'file': 'https://docs.google.com/uc?id=1Uk_gEPy-Oxskln9bV9lxKHyj4rZyYUFK' },
        { 'icon': iconImage, 'title': '아마츠키 - 월요일의 우울', 'file': 'https://docs.google.com/uc?id=1YzU90qMoFeuzcqEXXXQCgytovU2ng4DT' },
        { 'icon': iconImage, 'title': '아오하라이드 OST - 세계는 사랑에 빠져있어', 'file': 'https://docs.google.com/uc?id=1xWk4TtycP_K7f8eguVceq3QZytn1S8E3' },
        { 'icon': iconImage, 'title': '아이오아이 - 소나기', 'file': 'https://docs.google.com/uc?id=18qy8-hf5ZyVu8crQusQKbeae_I_88KSj' },
        { 'icon': iconImage, 'title': '안예은 - 홍연', 'file': 'https://docs.google.com/uc?id=1FolET5q-eeoFHTlbmjiduLW4K4F0Edie' },
        { 'icon': iconImage, 'title': '앨리샤 키스 - If ain_t got you', 'file': 'https://docs.google.com/uc?id=1ob9e4crp9QooptOPOdMSGYn-8r9obHac' },
        { 'icon': iconImage, 'title': '위대한 쇼맨 OST - This is me', 'file': 'https://docs.google.com/uc?id=1GynfPhuDVIjmvIiBVGejS8jAsNYLZyiI' },
        { 'icon': iconImage, 'title': '이선희 - 여우비', 'file': 'https://docs.google.com/uc?id=16n7tXvzeIIN3bJmn2Hum3I0OK_ZpNPG1' },
        { 'icon': iconImage, 'title': '이선희 - 인연', 'file': 'https://docs.google.com/uc?id=1WA7IRp0KjjK_HKNLCQQ6hIkQzFg6fjUk' },
        { 'icon': iconImage, 'title': '임세준 - 오늘은 가지마', 'file': 'https://docs.google.com/uc?id=1eXk0ba2IluKip8BPJq1Pkbno7s3MLCoS' },
        { 'icon': iconImage, 'title': '자우림 - 스물다섯 스물하나', 'file': 'https://docs.google.com/uc?id=1oIZ-CPdYEz3WafvPmmaZn6p88GG1oElW' },
        { 'icon': iconImage, 'title': '잔나비 - 주저하는 연인들을 위해', 'file': 'https://docs.google.com/uc?id=1aZEc1jd2Y3wCBW5Kn-vt4tSLh_rsjYQH' },
        { 'icon': iconImage, 'title': '정승환 - 너였다면', 'file': 'https://docs.google.com/uc?id=1mYXAsu0IcDQrERW-zizowegfqWAwdsMT' },
        { 'icon': iconImage, 'title': '타이타닉 OST - My heart will go on', 'file': 'https://docs.google.com/uc?id=1d37tgdnfHfZ8Nt1HV9_0eoJcxwHWam-Z' },
        { 'icon': iconImage, 'title': '태연 - 11  11', 'file': 'https://docs.google.com/uc?id=1jxjJ4-D6E7v-qcXXO-NBlA_16T_m6sQG' },
        { 'icon': iconImage, 'title': '파트너', 'file': 'https://docs.google.com/uc?id=1nkO3m9Z4NiJg63CVvEwhBVoXlvR_AJoF' },
        { 'icon': iconImage, 'title': '프래크 시나트라 -L.O.V.E (JAZZ)', 'file': 'https://docs.google.com/uc?id=14Xm62jccgyiZm9LHSVarQwryG_2csjHS' },
        { 'icon': iconImage, 'title': '프랭크 시나트라  - All of me', 'file': 'https://docs.google.com/uc?id=1tqOFK096QwgDhgHhp3MG_m-lP6fQLXjK' },
        { 'icon': iconImage, 'title': '프리즘스톤 OST - Blowin_ in the Mind (양자택일)', 'file': 'https://docs.google.com/uc?id=1mzAMz2218H4f0pqVcJo11-HDoYVfALyp' },
        { 'icon': iconImage, 'title': 'Ahoy!! 우리는 호쇼해적단☆', 'file': 'https://docs.google.com/uc?id=1pPQJ4selEIwmbHw3efewyawMtD81Wz40' },
        { 'icon': iconImage, 'title': 'Beyonce - Love On To', 'file': 'https://docs.google.com/uc?id=13T2SF8_EfoxzsAMsu9TLROGRX51WuMgP' },
        { 'icon': iconImage, 'title': 'Karina - Slow motion', 'file': 'https://docs.google.com/uc?id=12XRdrbKECI-LMY-glxP_lSNCovZTBD-s' },
        { 'icon': iconImage, 'title': 'KDA - POPSTAR', 'file': 'https://docs.google.com/uc?id=1dSc-y0xkozc81nQZYoX7iLtpMArRycYV' },
        { 'icon': iconImage, 'title': 'Mona - 팬서비스', 'file': 'https://docs.google.com/uc?id=1dQYb7Tv09zKPgfKRlsq3cxagac7tbneR' },
        { 'icon': iconImage, 'title': 'Sara Barielles - Gravity', 'file': 'https://docs.google.com/uc?id=1EpxeVCIrhyv9PVkCiphNfRMCviBTlU8w' },
        { 'icon': iconImage, 'title': 'Sia - Snowman', 'file': 'https://docs.google.com/uc?id=1inTMn7LvVdG4-OUun2WSOI1H2ax-NEPj' },
        
    ]
});