
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '10cm - pet', 'file': 'https://docs.google.com/uc?export=open&id=1sX1YTMYhHVqeDRbi5xX76W6Mqg9IOxMP' },
        { 'icon': iconImage, 'title': '김광진 - 편지', 'file': 'https://docs.google.com/uc?export=open&id=1MBvW75CIVlmcDCdYX0x3sZIh7su9VuUK' },
        { 'icon': iconImage, 'title': '호랑수월가', 'file': 'https://docs.google.com/uc?export=open&id=1WSYSyNeUfD3OeAMCjXbixNsNFZLSfC93' },
        { 'icon': iconImage, 'title': '아무것도 아니야', 'file': 'https://docs.google.com/uc?export=open&id=1qdPF46m4K5-ZGK1BJ8Uufh0rtO67paej' },
        { 'icon': iconImage, 'title': '염라', 'file': 'https://docs.google.com/uc?export=open&id=1NzXmeeMPJBX7T_6kG7oW1_fNHA5Jq6pO' },
        { 'icon': iconImage, 'title': 'Creep', 'file': 'https://docs.google.com/uc?export=open&id=1icqpsJu27k8GDhu_mLt7PZ7e9x05XWZn' },
        { 'icon': iconImage, 'title': '라푼젤 OST', 'file': 'https://docs.google.com/uc?export=open&id=1CmhyI0owc_xgUkpO3MVG9H6y2uOeSfKa' },
        { 'icon': iconImage, 'title': '폼포코링', 'file': 'https://docs.google.com/uc?export=open&id=1o4feAVLYs5QJtzb-IgTGwNKE0v8MRflI' },
        { 'icon': iconImage, 'title': 'When you beileve', 'file': 'https://docs.google.com/uc?export=open&id=1FpjoluBrDdCvu4Ob3afd1uvSIsMcAcbb' },
        { 'icon': iconImage, 'title': '레베카', 'file': 'https://docs.google.com/uc?export=open&id=1OwbUptH_WF29ndYFhvUWFBZ9O7KqAXBd' },
        { 'icon': iconImage, 'title': 'Defying Gravity', 'file': 'https://docs.google.com/uc?export=open&id=1vIDFh6UgVGjJ3e50CXajXKwamY_pxTQd' },
        { 'icon': iconImage, 'title': '캣츠', 'file': 'https://docs.google.com/uc?export=open&id=12c2KInYXktojj4w3ARatP8ovzJdgL7i-' },
        { 'icon': iconImage, 'title': '벤 - 꿈처럼', 'file': 'https://docs.google.com/uc?export=open&id=13-upc2zHIPWwoy_1iqzke-pSOfD6s0_C' },
        { 'icon': iconImage, 'title': '비욘세 - Listen', 'file': 'https://docs.google.com/uc?export=open&id=1dJAQdpnr5Tkp5nHGnT_XFCxV1GO_z_C9' },
        { 'icon': iconImage, 'title': '비챤생일축하', 'file': 'https://docs.google.com/uc?export=open&id=1IKJVybwyp9QJYSQlL60G2GnTcKIFQn3l' },
        { 'icon': iconImage, 'title': 'Lay me down', 'file': 'https://docs.google.com/uc?export=open&id=1TCb2oM6iih5-GyrAVtD2PL20oHfUD4Ll' },
        { 'icon': iconImage, 'title': '선우정아 - 도망가자', 'file': 'https://docs.google.com/uc?export=open&id=1z6F_2nzpX2W7tUJ3ja5yZfp66bl4RhOE' },
        { 'icon': iconImage, 'title': '성시경 - 너의 모든 순간', 'file': 'https://docs.google.com/uc?export=open&id=1lew1aXkeT4Mz9H1mNlDFh3itYeigZ5Lw' },
        { 'icon': iconImage, 'title': '송소희 - 달무리', 'file': 'https://docs.google.com/uc?export=open&id=12MlkxfZ2dehxdrFaVlG5kSp1HoSie-aS' },
        { 'icon': iconImage, 'title': '심규선 - 아라리', 'file': 'https://docs.google.com/uc?export=open&id=1t9lHwhDsiRFhhsvTH-8J1JUuqK3Zk2uV' },
        { 'icon': iconImage, 'title': '심규선 - 화조도', 'file': 'https://docs.google.com/uc?export=open&id=1TnmFEJ7MyGwlDX7_tkC-AVRT-6jX2fVo' },
        { 'icon': iconImage, 'title': '아델 - When we were young', 'file': 'https://docs.google.com/uc?export=open&id=16nNKkIcpELxcUkgBzm3PTWAu4okQiT6M' },
        { 'icon': iconImage, 'title': '그란데 - Dangerous Woman', 'file': 'https://docs.google.com/uc?export=open&id=1lmuWPPAh6IsBev2OYhlcOrJbllW8ewbM' },
        { 'icon': iconImage, 'title': '그란데 - almost is never enough', 'file': 'https://docs.google.com/uc?export=open&id=1GP1204AJiUE3M-Wp73V2w3yW8lQht30B' },
        { 'icon': iconImage, 'title': '그란데 - One last time', 'file': 'https://docs.google.com/uc?export=open&id=1j0Rcga1VnJlqqcdJ6fQxcQju1_ev8l0U' },
        { 'icon': iconImage, 'title': '아마츠키 - 월요일의 우울', 'file': 'https://docs.google.com/uc?export=open&id=10B6q2SarGiL9j3coRBxCTDAVZjalYZE5' },
        { 'icon': iconImage, 'title': '세계는 사랑에 빠져있어', 'file': 'https://docs.google.com/uc?export=open&id=1jJKkyW9gFJESjiqVFOTy4-wh4xLYD0BV' },
        { 'icon': iconImage, 'title': '아이오아이 - 소나기', 'file': 'https://docs.google.com/uc?export=open&id=1FadN9ktd6XNaDOoGv1qMWEk4QAJE4Guh' },
        { 'icon': iconImage, 'title': '안예은 - 홍연', 'file': 'https://docs.google.com/uc?export=open&id=1MBJgAxztNHhM5gWkaqwsGDSV3VO-tFwQ' },
        { 'icon': iconImage, 'title': '앨리샤 - if aint got you', 'file': 'https://docs.google.com/uc?export=open&id=1V5oF5DPCp9UaWm_OMtDvqUIPSdH2rjNb' },
        { 'icon': iconImage, 'title': '위대한 쇼맨 OST - This is me', 'file': 'https://docs.google.com/uc?export=open&id=1LflIHb_664Su-v5DEp2NAtOb8l1UNkz2' },
        { 'icon': iconImage, 'title': '이선희 - 여우비', 'file': 'https://docs.google.com/uc?export=open&id=1rYrusflNitf6ZCDSZkeMUC07gLe-v5mo' },
        { 'icon': iconImage, 'title': '이선희 - 인연', 'file': 'https://docs.google.com/uc?export=open&id=1JJFmM0K-yryQ3BBzAwMcAM3NCbA24l5P' },
        { 'icon': iconImage, 'title': '임세준 - 오늘은 가지마', 'file': 'https://docs.google.com/uc?export=open&id=13ib8-oCfgpVoj4-kNwtPTuU2mtl04IlS' },
        { 'icon': iconImage, 'title': '자우림 - 스물다섯 스물하나', 'file': 'https://docs.google.com/uc?export=open&id=1zz2tdtaqiVnAFt0q3zy3egDtek19nta7' },
        { 'icon': iconImage, 'title': '잔나비 - 주저하는 연인들을 위해', 'file': 'https://docs.google.com/uc?export=open&id=1ylk1jk6wOiIBTlzObezLdew3g9Oj2Er1' },
        { 'icon': iconImage, 'title': '정승환 - 너엿다면', 'file': 'https://docs.google.com/uc?export=open&id=1iOTmOHSzSaoPxV6X5v7w3pzVW5zAXd0w' },
        { 'icon': iconImage, 'title': '타이타닉 OST - My heart will go on', 'file': 'https://docs.google.com/uc?export=open&id=1dn99jLd-8KeA5mYZwFiymZLnR1ovK0P6' },
        { 'icon': iconImage, 'title': '태연 - 11:11', 'file': 'https://docs.google.com/uc?export=open&id=18P32nW3PlCIiCmyebc8kbW4zbpwh_b16' },
        { 'icon': iconImage, 'title': '파트너', 'file': 'https://docs.google.com/uc?export=open&id=1otSacj49UJdxIDe2-sZZQoiL7LfR2NR9' },
        { 'icon': iconImage, 'title': '프랭크 시나트라 - L.O.V.E', 'file': 'https://docs.google.com/uc?export=open&id=1DzfCs9PRj1h-yJgHpP07s6fFZfGX3EBR' },
        { 'icon': iconImage, 'title': '프랭크 시나트라 - All of me', 'file': 'https://docs.google.com/uc?export=open&id=1wwhMueRQg2OS5UPQHnzxkyrStwB8PFE2' },
        { 'icon': iconImage, 'title': '프리즘스톤 OST - 양자택일', 'file': 'https://docs.google.com/uc?export=open&id=1rkj9Laa4GZ5n2FVbB51g3TaxxG_-KJ0q' },
        { 'icon': iconImage, 'title': 'Ahoy', 'file': 'https://docs.google.com/uc?export=open&id=1aR14IYPnygvlxo0V7FzR03V20WAGLMoG' },
        { 'icon': iconImage, 'title': '비욘세 - Love On Top', 'file': 'https://docs.google.com/uc?export=open&id=14eYKkotSWMkOcWc5X_qmemz1omfkQimV' },
        { 'icon': iconImage, 'title': 'Karina - Slow motion', 'file': 'https://docs.google.com/uc?export=open&id=1MAY7IfGF0RfLGxPKGW8edtX7d6yBrQE1' },
        { 'icon': iconImage, 'title': 'KDA - POPSTAR', 'file': 'https://docs.google.com/uc?export=open&id=1CXlqCPuz-ngPYUC0IctfZ3wXwEAwWjFB' },
        { 'icon': iconImage, 'title': 'Mona - 팬서비스', 'file': 'https://docs.google.com/uc?export=open&id=1YqJHZFH7JOgixuEWgTgTA-ICDSrvvmOh' },
        { 'icon': iconImage, 'title': 'Sara - Gravity', 'file': 'https://docs.google.com/uc?export=open&id=1mwdGNFM6MB7TtFbjQ61eEhd0d_tl-mAf' },
        { 'icon': iconImage, 'title': 'Sia - Snowman', 'file': 'https://docs.google.com/uc?export=open&id=1xXbEvcq3fPlWEXlHSgE_OjYPdXVR5brl' },
        { 'icon': iconImage, 'title': 'TONES AND I - DANCE MONKEY', 'file': 'https://docs.google.com/uc?export=open&id=1KfkIMkdiBs8F_I0X58TDGVFVHVnaKpxu' },
        { 'icon': iconImage, 'title': 'Westlife -데스페라도', 'file': 'https://docs.google.com/uc?export=open&id=1ln_-jjxm_5tHKajinb4gdju2EhVozcX0' },
        { 'icon': iconImage, 'title': '겨울왕국2 - Show yourself', 'file': 'https://docs.google.com/uc?export=open&id=1OxkZTmnW7306ihnqEy5NuqfZG6f53IXo' },
        { 'icon': iconImage, 'title': '악동뮤지션 - 어떻게 이별까지 사랑하겠어', 'file': 'https://docs.google.com/uc?export=open&id=1gq3NwCd6VXLzH1CpqXM2Pjl6QlLx4uLc' },
    ]
});