
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '10cm - pet', 'file': '' },
        { 'icon': iconImage, 'title': '김광진 - 편지', 'file': '' },
        { 'icon': iconImage, 'title': '호랑수월가', 'file': '' },
        { 'icon': iconImage, 'title': '아무것도 아니야', 'file': '' },
        { 'icon': iconImage, 'title': '염라', 'file': '' },
        { 'icon': iconImage, 'title': 'Creep', 'file': '' },
        { 'icon': iconImage, 'title': '라푼젤 OST', 'file': '' },
        { 'icon': iconImage, 'title': '폼포코링', 'file': '' },
        { 'icon': iconImage, 'title': 'When you beileve', 'file': '' },
        { 'icon': iconImage, 'title': '레베카', 'file': '' },
        { 'icon': iconImage, 'title': 'Defying Gravity', 'file': '' },
        { 'icon': iconImage, 'title': '캣츠', 'file': '' },
        { 'icon': iconImage, 'title': '벤 - 꿈처럼', 'file': '' },
        { 'icon': iconImage, 'title': '비욘세 - Listen', 'file': '' },
        { 'icon': iconImage, 'title': '비챤생일축하', 'file': '' },
        { 'icon': iconImage, 'title': 'Lay me down', 'file': '' },
        { 'icon': iconImage, 'title': '선우정아 - 도망가자', 'file': '' },
        { 'icon': iconImage, 'title': '성시경 - 너의 모든 순간', 'file': '' },
        { 'icon': iconImage, 'title': '송소희 - 달무리', 'file': '' },
        { 'icon': iconImage, 'title': '심규선 - 아라리', 'file': '' },
        { 'icon': iconImage, 'title': '심규선 - 화조도', 'file': '' },
        { 'icon': iconImage, 'title': '아델 - When we were young', 'file': '' },
        { 'icon': iconImage, 'title': '그란데 - Dangerous Woman', 'file': '' },
        { 'icon': iconImage, 'title': '그란데 - almost is never enough', 'file': '' },
        { 'icon': iconImage, 'title': '그란데 - One last time', 'file': '' },
        { 'icon': iconImage, 'title': '아마츠키 - 월요일의 우울', 'file': '' },
        { 'icon': iconImage, 'title': '세계는 사랑에 빠져있어', 'file': '' },
        { 'icon': iconImage, 'title': '아이오아이 - 소나기', 'file': '' },
        { 'icon': iconImage, 'title': '안예은 - 홍연', 'file': '' },
        { 'icon': iconImage, 'title': '앨리샤 - if aint got you', 'file': '' },
        { 'icon': iconImage, 'title': '위대한 쇼맨 OST - This is me', 'file': '' },
        { 'icon': iconImage, 'title': '이선희 - 여우비', 'file': '' },
        { 'icon': iconImage, 'title': '이선희 - 인연', 'file': '' },
        { 'icon': iconImage, 'title': '임세준 - 오늘은 가지마', 'file': '' },
        { 'icon': iconImage, 'title': '자우림 - 스물다섯 스물하나', 'file': '' },
        { 'icon': iconImage, 'title': '잔나비 - 주저하는 연인들을 위해', 'file': '' },
        { 'icon': iconImage, 'title': '정승환 - 너엿다면', 'file': '' },
        { 'icon': iconImage, 'title': '타이타닉 OST - My heart will go on', 'file': '' },
        { 'icon': iconImage, 'title': '태연 - 11:11', 'file': '' },
        { 'icon': iconImage, 'title': '파트너', 'file': '' },
        { 'icon': iconImage, 'title': '프랭크 시나트라 - L.O.V.E', 'file': '' },
        { 'icon': iconImage, 'title': '프랭크 시나트라 - All of me', 'file': '' },
        { 'icon': iconImage, 'title': '프리즘스톤 OST - 양자택일', 'file': '' },
        { 'icon': iconImage, 'title': 'Ahoy', 'file': '' },
        { 'icon': iconImage, 'title': '비욘세 - Love On Top', 'file': '' },
        { 'icon': iconImage, 'title': 'Karina - Slow motion', 'file': '' },
        { 'icon': iconImage, 'title': 'KDA - POPSTAR', 'file': '' },
        { 'icon': iconImage, 'title': 'Mona - 팬서비스', 'file': '' },
        { 'icon': iconImage, 'title': 'Sara - Gravity', 'file': '' },
        { 'icon': iconImage, 'title': 'Sia - Snowman', 'file': '' },
        { 'icon': iconImage, 'title': 'TONES AND I - DANCE MONKEY', 'file': '' },
        { 'icon': iconImage, 'title': 'Westlife -데스페라도', 'file': '' },
        { 'icon': iconImage, 'title': '겨울왕국2 - Show yourself', 'file': '' },
        { 'icon': iconImage, 'title': '악동뮤지션 - 어떻게 이별까지 사랑하겠어', 'file': '' },
    ]
});