
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '비챤 - 드라이플라워', 'file': 'https://docs.google.com/uc?id=1c2JRO227mTYhVemiD4lviQbYnaoiVLDu' },
        { 'icon': iconImage, 'title': 'Back Number - クリスマスソング', 'file': 'https://docs.google.com/uc?id=1T4v2iIcmeKkoOfdDu897JGzVq8tZbZMY' },
        { 'icon': iconImage, 'title': '꿈빛파티시엘', 'file': 'https://docs.google.com/uc?id=14XwnGC67YQmi1ZJdduGnj3EWCgIDWNqk' },
        { 'icon': iconImage, 'title': '내발굽잡아', 'file': 'https://docs.google.com/uc?id=1fgLrCzLpwMVWtV9Cb9X24fcg-l_-dw-F' },
        { 'icon': iconImage, 'title': '너랑나', 'file': 'https://docs.google.com/uc?id=134dVPiixcbzvwGpR4cJRiAeeRXKSX34m' },
        { 'icon': iconImage, 'title': '넥스트레벨', 'file': 'https://docs.google.com/uc?id=1MRIHjkelkOwt5FEbIzWcLdhLn8s0tkBb' },
        { 'icon': iconImage, 'title': '똥밟았네', 'file': 'https://docs.google.com/uc?id=1-FwJ09h0QAVVJ4SUMaTFfALXqI2F9bK_' },
        { 'icon': iconImage, 'title': '분홍신', 'file': 'https://docs.google.com/uc?id=1ZUIyZI9GFDG6iEQGinZJKs20slrNItu1' },
        { 'icon': iconImage, 'title': '비밀의화원', 'file': 'https://docs.google.com/uc?id=1ybL3c25S9B1Yglc_T7AzB_eWJqRLbaix' },
        { 'icon': iconImage, 'title': '셀러브리티', 'file': 'https://docs.google.com/uc?id=1CAjktiHSAICm0fgASiGaHs1lKaW6SxJM' },
        { 'icon': iconImage, 'title': '에잇', 'file': 'https://docs.google.com/uc?id=1J58fAv-tSgvjKUnkt_L2lsOxD4VqrsKb' },
        { 'icon': iconImage, 'title': '일레븐', 'file': 'https://docs.google.com/uc?id=1EzXThUEvpnYsqWj3dNjFukofPHhbnzAw' },
        { 'icon': iconImage, 'title': '재즈', 'file': 'https://docs.google.com/uc?id=1LYPytpJ5CEg_70EocNFzJh1CoeIkKjIh' },
        { 'icon': iconImage, 'title': '급뱅종선언', 'file': 'https://docs.google.com/uc?id=1kAm2i3t5kRj7DqGgs9RS41p4fTK6H727' },
        { 'icon': iconImage, 'title': '부엉이', 'file': 'https://docs.google.com/uc?id=1OoPsWQLrlL1_s0_0q_AVMYKyU5lNd_eU' },
        { 'icon': iconImage, 'title': '잊혀지지못할언어', 'file': 'https://docs.google.com/uc?id=1kJTPpQpJeNb7KY_TKQbZHk3FywAUg30G' },
        { 'icon': iconImage, 'title': '염라', 'file': 'https://docs.google.com/uc?id=1TD4r2wVVzCMjZN688FJRVKCVHYTDkSJJ' },
        { 'icon': iconImage, 'title': '세계는 사랑에 빠져있어', 'file': 'https://docs.google.com/uc?id=1xnGgguZN3OqsnDP0syvaeH-2vhKXj_S-' },
        { 'icon': iconImage, 'title': '에반게리온 Beautiful World', 'file': 'https://docs.google.com/uc?id=1yD0UsDBOMt9fQpX-MZf612xc5PrgZYbl' },
        { 'icon': iconImage, 'title': '잔혹한 천사의 테제', 'file': 'https://docs.google.com/uc?id=1X1KLdHFzoN0Jhd0btGfDCjKwpNVuILCO' },
        { 'icon': iconImage, 'title': '네모의꿈', 'file': 'https://docs.google.com/uc?id=1qdLHsnT7P1HYdeDTYi9fwKCZqEnIVpcU' },
        { 'icon': iconImage, 'title': '라이키', 'file': 'https://docs.google.com/uc?id=1jdcs4IDzxlCUqWq4Zr8AGJyQ_ZmgXNjU' },
        { 'icon': iconImage, 'title': '롤린', 'file': 'https://docs.google.com/uc?id=1bjELgZwOi24Kh2_oe3wrOLC8KXFVPnuu' },
        { 'icon': iconImage, 'title': '롤링인더딥', 'file': 'https://docs.google.com/uc?id=1IrBozX7TwULVXXcAd1PgJSfsTaL8EaZS' },
        { 'icon': iconImage, 'title': '배드', 'file': 'https://docs.google.com/uc?id=1j8Jg6nEWK7G5wmPzP7RX4NlRdO0NWtJy' },
        { 'icon': iconImage, 'title': '샹들리에', 'file': 'https://docs.google.com/uc?id=1dQGrQ3om5tSvSdaHUlulTPaxxPOtj5JC' },
        { 'icon': iconImage, 'title': '스피치리스', 'file': 'https://docs.google.com/uc?id=1ElIFJtHOAKY2ozRsd33y26xZIngEARe5' },
        { 'icon': iconImage, 'title': '오르트구름', 'file': 'https://docs.google.com/uc?id=1Y1bbyX9GhQ3ANLvozSJBy7V4TioeEyZL' },
        { 'icon': iconImage, 'title': '오르트구름2', 'file': 'https://docs.google.com/uc?id=1w5Dx3CpCCfXpFosztIGTmIs1xhbneZMK' },
        { 'icon': iconImage, 'title': '우리의꿈 ', 'file': 'https://docs.google.com/uc?id=1KqdzKgzMEdOCihcELVRA2Jg-p4S_a0mQ' },
        { 'icon': iconImage, 'title': '창귀', 'file': 'https://docs.google.com/uc?id=1fLQVN5WurXPpG6ffMIc-oBRagvu7J8pL' },
        { 'icon': iconImage, 'title': '페인풀월드', 'file': 'https://docs.google.com/uc?id=12cwnmnfHfEyPPg4vrG6ifWuhbZX4Rho7' },
        { 'icon': iconImage, 'title': 'Let it go', 'file': 'https://docs.google.com/uc?id=1sDcKtCLttR2w_U7fUK-WL2b3tf6KjxVF' },
        { 'icon': iconImage, 'title': '이세돌 리와인드 화음버전', 'file': 'https://docs.google.com/uc?id=1cW-cPGeQpHBKqBSr9xjp3MUtLwMgRo-0' },
        { 'icon': iconImage, 'title': '07 TH - little', 'file': 'https://docs.google.com/uc?id=12_qWi1m2d75hHFdfigyFaVu1nWJDPW_z' },
        { 'icon': iconImage, 'title': '2021 12 21비챤 염라', 'file': 'https://docs.google.com/uc?id=1XNq6565PGQcgvUJ-zFiILSPsZwmTFxr_' },
        { 'icon': iconImage, 'title': '비챤 - 그래서 나는 음악을 그만두었다', 'file': 'https://docs.google.com/uc?id=1q6KXpvE1BPL79-sEGQg2P-9E1CzozwJW' },
        { 'icon': iconImage, 'title': '비챤 - 마이왁타버스 화음', 'file': 'https://docs.google.com/uc?id=1-d5j88-noyfcsrgYsg-0IK9UxGlvJXRR' },
        { 'icon': iconImage, 'title': '비챤 - 사랑을 전하고 싶다던가', 'file': 'https://docs.google.com/uc?id=1aSeC9gydqnPa1jSlegQ3932HdqKedy_q' },
        { 'icon': iconImage, 'title': '비챤 - 스물셋', 'file': 'https://docs.google.com/uc?id=1-d49Jzzwkvx7S6vbZr1x6QMVSXhdcSFb' },
        { 'icon': iconImage, 'title': '비챤 - 신호등', 'file': 'https://docs.google.com/uc?id=1hY7Mq2EUlP76WZtesMNlfKoWSmDu0Qah' },
        { 'icon': iconImage, 'title': '비챤 - Back Number 크리스마스송', 'file': 'https://docs.google.com/uc?id=1cthcNdfzpWU4wz9IQbiWW7_Ww7ifIRi9' },
        { 'icon': iconImage, 'title': '비챤- 이소라 Track9', 'file': 'https://docs.google.com/uc?id=18t6Fr613G_sn6J5JdfoVgQ7oFKMD4zJ7' },
        { 'icon': iconImage, 'title': '비챤- 이하이 홀로', 'file': 'https://docs.google.com/uc?id=1fBs-pMlpbuUA7f374dB3zrItt8-sWw-m' },
    ]
});