
// test image for web notifications
var iconImage = null;

AP.init({
    container: '#player',//a string containing one CSS selector
    volume: 0.7,
    autoPlay: false,
    notification: false,
    playList: [
        { 'icon': iconImage, 'title': '비챤 - 드라이플라워', 'file': 'https://docs.google.com/uc?id=1s00A96DrfqdIWkDrYLkrpAth8VdR4cuw' },
        { 'icon': iconImage, 'title': 'Back Number - クリスマスソング', 'file': 'https://docs.google.com/uc?id=13S1vOdDIatddurHmRtaVhcQ1YvP2Ah7r' },
        { 'icon': iconImage, 'title': '꿈빛파티시엘', 'file': 'https://docs.google.com/uc?id=12UeSjZARzxosHCGSdny-8mYIyV0xBTB-' },
        { 'icon': iconImage, 'title': '내발굽잡아', 'file': 'https://docs.google.com/uc?id=1k4u5kj4NXJGAO8QdaqShp1Ce7bBslc4G' },
        { 'icon': iconImage, 'title': '너랑나', 'file': 'https://docs.google.com/uc?id=1teVuh_8bjT9zQAKMO7jDycYF-ACbAUN7' },
        { 'icon': iconImage, 'title': '넥스트레벨', 'file': 'https://docs.google.com/uc?id=1594pptWfzq9UdslWO_m_UPqzBF6149Zt' },
        { 'icon': iconImage, 'title': '똥밟았네', 'file': 'https://docs.google.com/uc?id=1ekPHQvtastuRXYCp9S1ofIuiG4oQ9U-v' },
        { 'icon': iconImage, 'title': '분홍신', 'file': 'https://docs.google.com/uc?id=1h45zw-1QEvSA2BP57ilC6NT-koPiFqDl' },
        { 'icon': iconImage, 'title': '비밀의화원', 'file': 'https://docs.google.com/uc?id=13D5YCD84uGp9DPFKHRXnYjQyKgglT5FG' },
        { 'icon': iconImage, 'title': '셀러브리티', 'file': 'https://docs.google.com/uc?id=1_lZB2ICGYF7RaXPvRRZv9Q5_blTSy7Jo' },
        { 'icon': iconImage, 'title': '에잇', 'file': 'https://docs.google.com/uc?id=1z6bOHU3stnT7ajCBCsi3sZ4UNvGGlM_2' },
        { 'icon': iconImage, 'title': '일레븐', 'file': 'https://docs.google.com/uc?id=1Q3Ss6RKa6wkoadychgcY9eDQZEpVGNue' },
        { 'icon': iconImage, 'title': '재즈', 'file': 'https://docs.google.com/uc?id=1usHt8zsotLEWhJ-SZzIKSuFrbgf1Cmg2' },
        { 'icon': iconImage, 'title': '급뱅종선언', 'file': 'https://docs.google.com/uc?id=1d87bT4Bte6OOkmzTy-aF8hgwvI-eV-dT' },
        { 'icon': iconImage, 'title': '부엉이', 'file': 'https://docs.google.com/uc?id=1EUvsk20f0vl4-v8LMnyWpnlEn1_4abbZ' },
        { 'icon': iconImage, 'title': '잊혀지지못할언어', 'file': 'https://docs.google.com/uc?id=1coTMre2zcKsxcX9yoaoA71LZeoOL-bmG' },
        { 'icon': iconImage, 'title': '염라', 'file': 'https://docs.google.com/uc?id=1FzuQQ02xXWq1qZE66vOGJ56BFXvm1dBT' },
        { 'icon': iconImage, 'title': '세계는 사랑에 빠져있어', 'file': 'https://docs.google.com/uc?id=19YUJUgpDjowRGU8JsfPw6eMjGnPZkorE' },
        { 'icon': iconImage, 'title': '에반게리온 Beautiful World', 'file': 'https://docs.google.com/uc?id=1vz4FwrhAuvZiXSxsNbCXy1U_ikfH3oXz' },
        { 'icon': iconImage, 'title': '잔혹한 천사의 테제', 'file': 'https://docs.google.com/uc?id=12z1XGWHwvz_Z3PsOXCzc68MHGguMhEWd' },
        { 'icon': iconImage, 'title': '네모의꿈', 'file': 'https://docs.google.com/uc?id=14ZgcjNr4S5vnckTvcE4i2tF1hxcif7SO' },
        { 'icon': iconImage, 'title': '라이키', 'file': 'https://docs.google.com/uc?id=1_N8NCiyzVSbfBcocKAC8IiavzZaaKKk0' },
        { 'icon': iconImage, 'title': '롤린', 'file': 'https://docs.google.com/uc?id=1b6GZYGhTTyARa5Tf8UU4D846AY0iDxst' },
        { 'icon': iconImage, 'title': '롤링인더딥', 'file': 'https://docs.google.com/uc?id=1TkYWV8R7qSQXtoyTVFImA5G2Jv_WvzY5' },
        { 'icon': iconImage, 'title': '배드', 'file': 'https://docs.google.com/uc?id=1FDfaHCbnRNU7q2NyTF1fMuqQuFRNUSL7' },
        { 'icon': iconImage, 'title': '샹들리에', 'file': 'https://docs.google.com/uc?id=1UxMQteOQvtwckds1VCuYWZoxKdFeHdVU' },
        { 'icon': iconImage, 'title': '스피치리스', 'file': 'https://docs.google.com/uc?id=16LVIS0hu6k0kX0Fk74AIAIB-5s1MrgTk' },
        { 'icon': iconImage, 'title': '오르트구름', 'file': 'https://docs.google.com/uc?id=1DtSlxxARKM-gKdah-Ha-lAgzOyhrVitQ' },
        { 'icon': iconImage, 'title': '오르트구름2', 'file': 'https://docs.google.com/uc?id=1Ta9NDLNUP8EZlHPaC9TLnx7sl-lvy5xq' },
        { 'icon': iconImage, 'title': '우리의꿈 ', 'file': 'https://docs.google.com/uc?id=1_S8meG2Llq66Gb820F2tiOEP7mmgEmeL' },
        { 'icon': iconImage, 'title': '창귀', 'file': 'https://docs.google.com/uc?id=1rfDhYsKSvvjkaHjdUiDRa-tX5-84KI8l' },
        { 'icon': iconImage, 'title': '페인풀월드', 'file': 'https://docs.google.com/uc?id=1jUO4IDwmpKmcg4kaEg5DhKbxtKGR-VvK' },
        { 'icon': iconImage, 'title': 'Let it go', 'file': 'https://docs.google.com/uc?id=1PSpt7Jrp9YMnEVkRgMG0tkJh7eVVYE0t' },
        { 'icon': iconImage, 'title': '이세돌 리와인드 화음버전', 'file': 'https://docs.google.com/uc?id=19jl8Sx0QMSNWCarEwh3wuNrWrOHaF5PQ' },
        { 'icon': iconImage, 'title': '07 TH - little', 'file': 'https://docs.google.com/uc?id=1iPSdwRbUFFZSCwlhFZIo3rbi4FFGEID_' },
        { 'icon': iconImage, 'title': '2021 12 21비챤 염라', 'file': 'https://docs.google.com/uc?id=1hT1M-mbDvOsAg9Q7ShD0kLOkujUc264k' },
        { 'icon': iconImage, 'title': '비챤 - 그래서 나는 음악을 그만두었다', 'file': 'https://docs.google.com/uc?id=1QEyHVTnI6i4hRgXux-GgMqSZTasaGM2b' },
        { 'icon': iconImage, 'title': '비챤 - 마이왁타버스 화음', 'file': 'https://docs.google.com/uc?id=1aTAb30zNlH0KgXLq4-66kkBLtpIliHgo' },
        { 'icon': iconImage, 'title': '비챤 - 사랑을 전하고 싶다던가', 'file': 'https://docs.google.com/uc?id=1ee2E4RzsADFghv4cnWhpQiDG2pKLjlaT' },
        { 'icon': iconImage, 'title': '비챤 - 스물셋', 'file': 'https://docs.google.com/uc?id=1EJplv1K-9R9rL5mfve-d1WseE-PjFkgJ' },
        { 'icon': iconImage, 'title': '비챤 - 신호등', 'file': 'https://docs.google.com/uc?id=1WK8V78a4jTzXzF76nHJnmBChW1IpJtHZ' },
        { 'icon': iconImage, 'title': '비챤 - Back Number 크리스마스송', 'file': 'https://docs.google.com/uc?id=16S3nWCWsHeHDlj0nq1ukYtuPAIOzFfVd' },
        { 'icon': iconImage, 'title': '비챤- 이소라 Track9', 'file': 'https://docs.google.com/uc?id=1WlzMQrk6WaavDyhnYLOmVzf7ZttNJNWE' },
        { 'icon': iconImage, 'title': '비챤- 이하이 홀로', 'file': 'https://docs.google.com/uc?id=1-3nOPQDVDPN0IjkmILiXOPcQ0d-iFLxK' },
        { 'icon': iconImage, 'title': '2NE1 - 그리워해요', 'file': 'https://docs.google.com/uc?id=1hYm9vgulpjsKmhkPN7cfpWar1wVmHdkW' },
        { 'icon': iconImage, 'title': '괴도키드ost - 사랑의 시나리오', 'file': 'https://docs.google.com/uc?id=1QCpfD8NKf9fuvFoFgRp3mkrsv-wRv8Dt' },
        { 'icon': iconImage, 'title': '김범수 - 보고싶다', 'file': 'https://docs.google.com/uc?id=1MkFzF0ClZetwhOqa6ADzNM1SAglxih9O' },
        { 'icon': iconImage, 'title': '도메스틱한 그녀 OP - 목마름을 외치다', 'file': 'https://docs.google.com/uc?id=1UJ-ajxZ40jrWKk9UVSk77gBbQsbY2z5E' },
        { 'icon': iconImage, 'title': '부엉이', 'file': 'https://docs.google.com/uc?id=1HjAB4pv6ML7inR7VTo2MmfL4fYN2EOVT' },
        { 'icon': iconImage, 'title': '블랙핑크 - Lovesick girls', 'file': 'https://docs.google.com/uc?id=1LAf91WX9erijGYe4YbVMr6sPqLIUrqJe' },
        { 'icon': iconImage, 'title': '빅뱅 - 붉은노을', 'file': 'https://docs.google.com/uc?id=15VgtQdKk9tf35dORopRE4yGXxWZ8Vy6S' },
        { 'icon': iconImage, 'title': '신세기 에반게리온 op - 잔혹한 천사의 테제', 'file': 'https://docs.google.com/uc?id=1x6nKx1_zBb-JAaZ0Q1-x73kUD8btKFM7' },
        { 'icon': iconImage, 'title': '아이유 - 내 손을 잡아', 'file': 'https://docs.google.com/uc?id=1YV5yh8j-QFxNzWDHyG0useqOFs7Jvdmb' },
        { 'icon': iconImage, 'title': '아이유 - 어푸', 'file': 'https://docs.google.com/uc?id=1ytSAGwe0uJRu0odpUHJk8j7DeUuaaOOO' },
        { 'icon': iconImage, 'title': '안예은 - 홍연', 'file': 'https://docs.google.com/uc?id=1n0syxteYoD2VcJPpH65yu6TdIrVSbnIY' },
        { 'icon': iconImage, 'title': '안예은 창귀', 'file': 'https://docs.google.com/uc?id=1m2IW5OCNyL3ZviqeEsX-zZELulHNWtBN' },
        { 'icon': iconImage, 'title': '월피스카터 - 공주열차', 'file': 'https://docs.google.com/uc?id=14m1F_EyzrvSQ0dHSEt58yG9GYsq4wDsM' },
        { 'icon': iconImage, 'title': '월피스카터 - 진흙 속에 피다', 'file': 'https://docs.google.com/uc?id=1J1dCVWAgBYxgHPnyKryXXrN0NKxWhs1E' },
        { 'icon': iconImage, 'title': '월피스카터 - 천성의 약함', 'file': 'https://docs.google.com/uc?id=19hIWUzGpKypFgKYU1DEIy1o28PuOZADR' },
        { 'icon': iconImage, 'title': '윤하 - 오르트구름', 'file': 'https://docs.google.com/uc?id=1w954lfRGjAGNB-Ywp9iHtdpbVyERI3lA' },
        { 'icon': iconImage, 'title': '이선희 - 인연', 'file': 'https://docs.google.com/uc?id=1sFmpqA-apMg4K2NpMTZQjTxyCkygmSQ1' },
        { 'icon': iconImage, 'title': '이키모노가카리 - Blue Bird (나루토 질풍전 3기 OP)', 'file': 'https://docs.google.com/uc?id=1a4ueRBWkMrazQQMup0Pu7N8y_UPBqCO5' },
        { 'icon': iconImage, 'title': '추노ost - 낙인', 'file': 'https://docs.google.com/uc?id=1V4mbmC6phCUe2eKa3knafnE5e9GInCMm' },
        { 'icon': iconImage, 'title': '카구야님은 고백받고 싶어 -반짝반짝 치카치카', 'file': 'https://docs.google.com/uc?id=1gmprbx8u7StsB30Jex41JkR-9k-Y-4oe' },
        { 'icon': iconImage, 'title': '태연 - I', 'file': 'https://docs.google.com/uc?id=1GzP00V24JJTX6au9kIUdK87KVHYUykgm' },
        { 'icon': iconImage, 'title': '태연 - Rain', 'file': 'https://docs.google.com/uc?id=1q3rX92gTBJj-eBkb7J7Zsks2OKuBXT-M' },
        { 'icon': iconImage, 'title': '하츠네 미쿠 - 연애재판', 'file': 'https://docs.google.com/uc?id=1HT1aqmeGeMW9O42XO047DweNP9dHf4Re' },
        { 'icon': iconImage, 'title': '혈계전선Ed - 슈가송과 비터스텝', 'file': 'https://docs.google.com/uc?id=1D__Cefxy95R_srXzBMocqjpkQXAmZM4K' },
        { 'icon': iconImage, 'title': '휘성 - 결혼까지생각했어', 'file': 'https://docs.google.com/uc?id=1dYCV-T8rWdONsKjT3bdFh1gYbUD4TZ5z' },
        { 'icon': iconImage, 'title': 'Ado - うっせぇわ(시끄러워)', 'file': 'https://docs.google.com/uc?id=19Gr3kzWQWlHUSUJKR3pjkGsB7X6JC3pU' },
        { 'icon': iconImage, 'title': 'Aimer - 잔향산가', 'file': 'https://docs.google.com/uc?id=1aw34jmCo2uR8Tc3DciTVxhbQr71oYahm' },
        { 'icon': iconImage, 'title': 'CHICO with HoneyWorks - 세계는 사랑에 빠져있어 (online-audio-converter.com)', 'file': 'https://docs.google.com/uc?id=1k72ttA_9fH_tFvq022YXtZfK2PAyEfxx' },
        { 'icon': iconImage, 'title': 'EGOIST - 이름없는괴물 (사이코패스 ED)', 'file': 'https://docs.google.com/uc?id=1DBdD9BOQZxUrZpcpYuM5ZfcANH-RQCJt' },
        { 'icon': iconImage, 'title': 'GOD - 촛불하나', 'file': 'https://docs.google.com/uc?id=15EfKKxzhW9-nZ22DCCJ0Du4KRGCySiw9' },
        { 'icon': iconImage, 'title': 'LISA - 불꽃', 'file': 'https://docs.google.com/uc?id=1iz_OBw1Q4MEV-n9tW4FUZQAuBsQv3GBG' },
        { 'icon': iconImage, 'title': 'LISA - 홍련화', 'file': 'https://docs.google.com/uc?id=13CmopbkP8MiVyhB_Mx7Cteh4PkoLTNPl' },
    ]
});